Repository music-assistant/server, pull requests merged in 2023-11, with the labels that each got.

#911 add missing session object to add/remove from library
  music_assistant/server/providers/tidal/__init__.py
Labels: bugfix

#903 Fix config for addon update action
  .github/workflows/release.yml
Labels: ci

#909 Adjust volume normalisation default
  music_assistant/common/models/config_entries.py
Labels: enhancement, maintenance

#918 Fix overriding global log level on module level
  music_assistant/server/models/core_controller.py
  music_assistant/server/providers/chromecast/__init__.py
Labels: maintenance

#919 Fix some issues with Airplay provider
  music_assistant/server/providers/airplay/__init__.py
Labels: bugfix, maintenance

#921 Fix issues with debouncing commands to (group)players
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/ugp/__init__.py
Labels: bugfix

#920 [soundcloud] bug fix: add limit parameter to get_recommended function
  music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
Labels: bugfix

#923 Fix cast player playing duplicate songs
  music_assistant/server/providers/chromecast/__init__.py
Labels: bugfix
