Repository music-assistant/server, pull requests merged in 2023-08, with the labels that each got.

#807 Various small bugfixes and improvements
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/database.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/providers/url/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: bugfix, maintenance

#808 Bump frontend to version 2.0.9
  pyproject.toml
  requirements_all.txt
Labels: dependencies, maintenance

#814 Fix for Tidal tracks listings
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/tidal/__init__.py
Labels: bugfix

#816 Make all models initializable by kwargs only
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: maintenance

#817 Several (small) Bugfixes
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/didl_lite.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/url/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: bugfix

#818 A few small bugfixes
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/providers/ytmusic/helpers.py
Labels: bugfix

#820 Improve Browse feature
  music_assistant/client/music.py
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/music.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/radiobrowser/__init__.py
Labels: maintenance

#822 add job to update addon version
  .github/workflows/release.yml
Labels: ci

#843 Some small fixes for audio sync and player groups
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: bugfix

#801 [Deezer] Switch to async library
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/helpers.py
  music_assistant/server/providers/deezer/manifest.json
  requirements_all.txt
Labels: refactor, python

#846 [Deezer] Implement radio mode
  music_assistant/server/providers/deezer/__init__.py
Labels: new-feature, python

#847 [Deezer] Fix search
  music_assistant/server/providers/deezer/manifest.json
  requirements_all.txt
Labels: bugfix, dependencies, python

#848 Fix similar tracks function
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: bugfix
