Repository music-assistant/server, pull requests merged in 2023-10, with the labels that each got.

#863 [Deezer] Fix sync album if no cover image
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/manifest.json
  requirements_all.txt
Labels: bugfix, dependencies, python

#868 FIx cumbersome restart, add idx to album tracks
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/plex/helpers.py
Labels: breaking-change, enhancement, refactor, bugfix

#898 update release action
  .github/workflows/release.yml
Labels: ci

#901 A few small fixes
  music_assistant/client/music.py
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/provider.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/players.py
  music_assistant/server/server.py
Labels: bugfix
