Repository music-assistant/server, pull requests merged in 2023-07, with the labels that each got.

#744 Improve CI workflow
  .github/release-drafter.yml
  .github/workflows/docker-build.yml
  .github/workflows/pr-labels.yaml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ci

#770 Some small bugfixes and improvements
  .github/workflows/release.yml
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: bugfix

#786 Fix play from here for playlists and albums
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/player_queues.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement, bugfix

#787 [Deezer] Fix parsing the tracks
  music_assistant/server/providers/deezer/__init__.py
Labels: bugfix, maintenance, python

#800 Some fixes for dlna based players
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/didl_lite.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/sonos/__init__.py
Labels: bugfix, maintenance
