Repository music-assistant/server, pull requests merged in 2023-12, with the labels that each got.

#954 frontend-2.0.16
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#953 Improve Filesystem provider
  music_assistant/common/models/enums.py
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/models/metadata_provider.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/icon.svg
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/slimproto/cli.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  tests/test_tags.py
Labels: enhancement, maintenance

#955 Fix snapcast provider in the dynamic generation of tcp streams
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#957 Fixing pyproject.toml
  pyproject.toml
Labels: bugfix

#959 Fix status of child players
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#967 Update manifest files for several providers
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/tunein/manifest.json
  music_assistant/server/providers/ugp/manifest.json
Labels: enhancement, maintenance

#968 Fix typo in TuneIn init/py
  music_assistant/server/providers/tunein/__init__.py
Labels: maintenance

#979 Retain extra url keys
  music_assistant/server/providers/url/__init__.py
Labels: bugfix

#980 A few small bugfixes
  music_assistant/common/models/queue_item.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/players.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/tunein/__init__.py
Labels: bugfix

#982 Fix playback of radio stations
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
Labels: bugfix
