Repository music-assistant/server, pull requests merged in 2024-09, with the labels that each got.

#1642 Some small bugfixes and tweaks
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1643 frontend-2.8.12
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1644 fix: 🐛 Hopefully fix release
  .github/workflows/release.yml
  Dockerfile
Labels: bugfix, ci

#1645 fix: 🐛 move download to after checkout, fix conditionals
  .github/workflows/release.yml
  Dockerfile
Labels: bugfix, ci

#1647 Split up build workflow to use intermediate base image
  .github/workflows/build-base-image.yml
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.base
Labels: ci

#1648 fix: 🐛 explicitly add dist to build context, ls contents
  Dockerfile
Labels: bugfix

#1649 chore: 🤖 cleanup dist folder after image is built
  Dockerfile
Labels: ci

#1650 Add Ukrainian to supported (metadata) languages
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1651 Fix playback get stuck when there is a stream error on a single track
  music_assistant/common/models/streamdetails.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1652 Apple Music: Various fixes
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1653 Fix several issues with enqueueing of next track
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/enums.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/_template_player_provider/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos_s1/__init__.py
  music_assistant/server/providers/sonos_s1/player.py
Labels: enhancement, bugfix

#1654 Feature: Radio mode enhancements
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/player_queues.py
Labels: enhancement

#1657 Volume normalization improvements
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/streamdetails.py
  music_assistant/constants.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement

#1658 Fix cast/dlna player stops playing after 1 or 2 tracks of a playlist
  music_assistant/server/controllers/player_queues.py
Labels: bugfix

#1661 frontend-2.8.13
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1662 Fix API compatibility
  music_assistant/common/models/player.py
  music_assistant/common/models/queue_item.py
  music_assistant/constants.py
  music_assistant/server/controllers/player_queues.py
Labels: enhancement, bugfix

#1663 Try parsing track number from the filename
  music_assistant/server/helpers/tags.py
Labels: enhancement

#1670 A few small bugfixes and enhancements to playback and enqueuing
  music_assistant/common/helpers/util.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  tests/test_helpers.py
Labels: enhancement, bugfix

#1672 Fix: flow mode not being applied in all cases (while it should)
  music_assistant/server/controllers/player_queues.py
Labels: bugfix

#1674 Fix keyerror in cache autocleanup
  music_assistant/server/controllers/cache.py
Labels: bugfix

#1675 Maintenance: Replace pylint with ruff
  .pre-commit-config.yaml
  Dockerfile
  music_assistant/__main__.py
  music_assistant/common/helpers/util.py
  music_assistant/common/models/api.py
  music_assistant/common/models/event.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/helpers/api.py
  music_assistant/server/helpers/app_vars.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/images.py
  music_assistant/server/helpers/logging.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/webserver.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/chromecast/helpers.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/sonos_s1/helpers.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/server.py
  pyproject.toml
Labels: ci, maintenance

#1676 Better handling of Spotify stream error (due to token expiration)
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/ffmpeg.py
  music_assistant/server/providers/spotify/__init__.py
Labels: bugfix

#1680 Bump base image to 1.0.10
  .github/workflows/release.yml
Labels: enhancement

#1682 Drop root during base image build and use venv
  .github/workflows/release.yml
  Dockerfile.base
Labels: ci, maintenance

#1683 fix: album directory parsing with album versions
  music_assistant/server/providers/filesystem_local/helpers.py
  tests/server/providers/filesystem/test_helpers.py
Labels: bugfix
