Repository music-assistant/server, pull requests merged in 2024-02, with the labels that each got.

#1061 Fix the browsing error for album tracks
  music_assistant/client/music.py
Labels: bugfix

#1056 Subsonic: Implement features required by Nextcloud Music support
  music_assistant/server/providers/opensubsonic/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: maintenance

#1057 Tidal typing
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: maintenance

#1071 Add support for Python 3.12 + fix issues with type checking
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/server.py
  pyproject.toml
Labels: enhancement, ci, maintenance

#1077 Add Home Assistant player provider
  music_assistant/common/helpers/datetime.py
  music_assistant/server/controllers/config.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass/icon.svg
  music_assistant/server/providers/hass/manifest.json
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/hass_players/icon.svg
  music_assistant/server/providers/hass_players/manifest.json
  requirements_all.txt
Labels: new-provider

#1007 Add Jellyfin Music Provider
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
  music_assistant/server/providers/jellyfin/icon.svg
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: new-provider

#1078 frontend-2.2.0
  music_assistant/server/providers/dlna/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1079 Bump hass client to 1.0.1
  music_assistant/server/providers/hass/manifest.json
  requirements_all.txt
Labels: bugfix, dependencies

#1080 frontend-2.2.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1081 Bugfix for skipped track when playing an artist or album
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/player_queues.py
Labels: bugfix

#1082 Fix HomeAssistant provider on supervised installs
  music_assistant/server/providers/hass/__init__.py
Labels: bugfix

#1083 Change documentation links
  music_assistant/server/providers/airplay/manifest.json
  music_assistant/server/providers/chromecast/manifest.json
  music_assistant/server/providers/deezer/manifest.json
  music_assistant/server/providers/dlna/manifest.json
  music_assistant/server/providers/filesystem_local/manifest.json
  music_assistant/server/providers/filesystem_smb/manifest.json
  music_assistant/server/providers/fully_kiosk/manifest.json
  music_assistant/server/providers/jellyfin/manifest.json
  music_assistant/server/providers/opensubsonic/manifest.json
  music_assistant/server/providers/plex/manifest.json
  music_assistant/server/providers/qobuz/manifest.json
  music_assistant/server/providers/radiobrowser/manifest.json
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/snapcast/manifest.json
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/soundcloud/manifest.json
  music_assistant/server/providers/spotify/manifest.json
  music_assistant/server/providers/tidal/manifest.json
  music_assistant/server/providers/tunein/manifest.json
  music_assistant/server/providers/ugp/manifest.json
  music_assistant/server/providers/url/manifest.json
  music_assistant/server/providers/ytmusic/manifest.json
Labels: maintenance

#1085 Add missing pyatv dependency
  pyproject.toml
  requirements_all.txt
Labels: bugfix

#1086 Fix Airplay playback on docker/haos installs
  music_assistant/common/models/provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/server.py
Labels: bugfix

#1088 Some more fixes for the Airplay provider
  music_assistant/server/providers/airplay/__init__.py
Labels: bugfix, maintenance

#1089 frontend-2.2.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1090 [Deezer] Allow user to manually input arl token, temporary fix
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/gw_client.py
  music_assistant/server/providers/deezer/manifest.json
  requirements_all.txt
Labels: refactor, bugfix, python

#1091 Airplay fixes
  music_assistant/server/models/provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
Labels: bugfix, maintenance

#1092 A collection of small bugfixes and optimizations
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/player.py
  music_assistant/common/models/player_queue.py
  music_assistant/common/models/provider.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/server.py
  pyproject.toml
Labels: enhancement, bugfix, maintenance

#1099 Fixes for the Active source being wrong in some cases
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/chromecast/helpers.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/sonos/player.py
  music_assistant/server/providers/spotify/__init__.py
Labels: bugfix

#1100 More improvements for the Airplay provider
  music_assistant/common/models/provider.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/images.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/airplay/manifest.json
  music_assistant/server/providers/chromecast/manifest.json
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1101 frontend-2.3.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1102 Change documentation link again
  music_assistant/server/providers/airplay/manifest.json
  music_assistant/server/providers/chromecast/manifest.json
  music_assistant/server/providers/deezer/manifest.json
  music_assistant/server/providers/dlna/manifest.json
  music_assistant/server/providers/filesystem_local/manifest.json
  music_assistant/server/providers/filesystem_smb/manifest.json
  music_assistant/server/providers/fully_kiosk/manifest.json
  music_assistant/server/providers/jellyfin/manifest.json
  music_assistant/server/providers/opensubsonic/manifest.json
  music_assistant/server/providers/plex/manifest.json
  music_assistant/server/providers/qobuz/manifest.json
  music_assistant/server/providers/radiobrowser/manifest.json
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/snapcast/manifest.json
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/soundcloud/manifest.json
  music_assistant/server/providers/spotify/manifest.json
  music_assistant/server/providers/tidal/manifest.json
  music_assistant/server/providers/tunein/manifest.json
  music_assistant/server/providers/ugp/manifest.json
  music_assistant/server/providers/url/manifest.json
  music_assistant/server/providers/ytmusic/manifest.json
Labels: maintenance

#1104 [Deezer]: Fix search
  music_assistant/server/providers/deezer/__init__.py
Labels: bugfix, python

#1105 frontend-2.3.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1107 Some optimizations for Airplay streaming
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: enhancement, bugfix, maintenance

#1109 Add verbose log level
  music_assistant/common/models/config_entries.py
  music_assistant/server/models/core_controller.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/sonos/__init__.py
Labels: maintenance

#1110 frontend-2.3.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1117 Some small bugfixes and enhancements
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/providers/airplay/__init__.py
Labels: bugfix, maintenance
