Repository music-assistant/server, pull requests merged in 2024-10, with the labels that each got.

#1690 Update to snapweb v0.8.0
  music_assistant/server/providers/snapcast/snapweb/assets/index-BYMjFABP.js
  music_assistant/server/providers/snapcast/snapweb/assets/index-DDLZhQdU.js
  music_assistant/server/providers/snapcast/snapweb/index.html
  music_assistant/server/providers/snapcast/snapweb/manifest.webmanifest
  music_assistant/server/providers/snapcast/snapweb/registerSW.js
  music_assistant/server/providers/snapcast/snapweb/sw.js
Labels: maintenance

#1692 Snapcast: Add configuration options
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement

#1702 Snapcast: Ensures the default stream exists
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1703 frontend-2.9.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1706 Additional logic and fixes for new group handling
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/player_group/__init__.py
  music_assistant/server/providers/sonos_s1/__init__.py
Labels: enhancement, bugfix

#1707 frontend-2.9.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1715 frontend-2.9.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1681 Add 'Don't stop the music' feature
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
Labels: new-feature

#1716 Some more bugfixes and tweaks for playergroups support
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/player_group/__init__.py
Labels: bugfix

#1717 Update apple music token
  music_assistant/server/helpers/app_vars.py
Labels: bugfix

#1722 Update tidalapi library to 0.8.0
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/manifest.json
  requirements_all.txt
Labels: breaking-change, refactor, dependencies

#1718 Refactor SnapCastProvider cmd_volume_mute method
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1724 frontend-2.9.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1725 frontend-2.9.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1726 frontend-2.9.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1727 Fix parsing of HLS (sub)streams
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/playlists.py
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1728 Various fixes and enhancements for (TTS) Announcemens
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/_template_player_provider/__init__.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/bluesound/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/player_group/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos_s1/__init__.py
Labels: enhancement, bugfix

#1729 frontend-2.9.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1730 Add SiriusXM Music Provider
  music_assistant/server/providers/siriusxm/__init__.py
  music_assistant/server/providers/siriusxm/icon.svg
  music_assistant/server/providers/siriusxm/icon_dark.svg
  music_assistant/server/providers/siriusxm/manifest.json
  requirements_all.txt
Labels: new-provider

#1739 SiriusXM: live radio data in the stream title
  music_assistant/server/providers/siriusxm/__init__.py
Labels: enhancement

#1742 Revert to snapweb v5
  music_assistant/server/providers/snapcast/snapweb/10-seconds-of-silence.mp3
  music_assistant/server/providers/snapcast/snapweb/3rd-party/libflac.js
  music_assistant/server/providers/snapcast/snapweb/apple-touch-icon-180x180.png
  music_assistant/server/providers/snapcast/snapweb/assets/index-BDBx6C_I.css
  music_assistant/server/providers/snapcast/snapweb/assets/index-BYMjFABP.js
  music_assistant/server/providers/snapcast/snapweb/assets/logo192-wKJb_L8G.png
  music_assistant/server/providers/snapcast/snapweb/config.js
  music_assistant/server/providers/snapcast/snapweb/favicon.ico
  music_assistant/server/providers/snapcast/snapweb/index.html
  music_assistant/server/providers/snapcast/snapweb/launcher-icon.png
  music_assistant/server/providers/snapcast/snapweb/logo.svg
  music_assistant/server/providers/snapcast/snapweb/manifest.json
  music_assistant/server/providers/snapcast/snapweb/manifest.webmanifest
  music_assistant/server/providers/snapcast/snapweb/maskable-icon-512x512.png
  music_assistant/server/providers/snapcast/snapweb/mute_icon.png
  music_assistant/server/providers/snapcast/snapweb/play.png
  music_assistant/server/providers/snapcast/snapweb/pwa-192x192.png
  music_assistant/server/providers/snapcast/snapweb/pwa-512x512.png
  music_assistant/server/providers/snapcast/snapweb/pwa-64x64.png
  music_assistant/server/providers/snapcast/snapweb/registerSW.js
  music_assistant/server/providers/snapcast/snapweb/robots.txt
  music_assistant/server/providers/snapcast/snapweb/snapcast-512.png
  music_assistant/server/providers/snapcast/snapweb/snapcontrol.js
  music_assistant/server/providers/snapcast/snapweb/snapstream.js
  music_assistant/server/providers/snapcast/snapweb/speaker_icon.png
  music_assistant/server/providers/snapcast/snapweb/stop.png
  music_assistant/server/providers/snapcast/snapweb/styles.css
  music_assistant/server/providers/snapcast/snapweb/sw.js
  music_assistant/server/providers/snapcast/snapweb/workbox-3e911b1d.js
Labels: maintenance

#1744 Several improvements to the queue controller
  music_assistant/common/models/enums.py
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/player_group/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/const.py
  music_assistant/server/providers/sonos_s1/__init__.py
Labels: enhancement, bugfix

#1743 Snapcast fix short announcements
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1745 frontend-v2.9.10
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1746 Fix docs links
  music_assistant/server/providers/bluesound/manifest.json
  music_assistant/server/providers/player_group/manifest.json
Labels: maintenance

#1747 Fix track enqueuing
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
Labels: bugfix

#1748 frontend-v2.9.11
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1756 fix: snapcast player in universal player group
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1757 frontend-v2.9.14
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release
