Repository music-assistant/server, pull requests merged in 2024-12, with the labels that each got.

#1811 Fix group players: No players available to form sync group
  music_assistant/providers/player_group/__init__.py
Labels: bugfix

#1806 Allow Chromecast provider to handle/avoid images which are "too big"
  music_assistant/controllers/player_queues.py
  music_assistant/providers/chromecast/__init__.py
  scripts/setup.sh
Labels: enhancement, bugfix

#1812 frontend-2.9.17
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1802 Subsonic: Add Podcast Support
  music_assistant/controllers/music.py
  music_assistant/models/music_provider.py
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: new-feature
