Repository music-assistant/server, pull requests merged in 2024-07, with the labels that each got.

#1426 Fetch larger version of Soundcloud artwork
  music_assistant/server/providers/soundcloud/__init__.py
Labels: enhancement, bugfix

#1428 Mypy: Add music_assistant.common
  music_assistant/client/music.py
  music_assistant/common/helpers/datetime.py
  music_assistant/common/helpers/global_cache.py
  music_assistant/common/helpers/json.py
  music_assistant/common/helpers/uri.py
  music_assistant/common/helpers/util.py
  music_assistant/common/models/api.py
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/errors.py
  music_assistant/common/models/media_items.py
  music_assistant/common/models/player.py
  music_assistant/common/models/player_queue.py
  music_assistant/common/models/provider.py
  music_assistant/common/models/queue_item.py
  music_assistant/server/providers/plex/__init__.py
  mypy.ini
Labels: ci, maintenance

#1434 Snapcast: Add delay, before so that the stream does not idle immediately
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1419 Snapcast remove check for 0.27
  music_assistant/server/providers/snapcast/__init__.py
Labels: maintenance

#1441 Snapcast remove unused code
  music_assistant/server/providers/snapcast/__init__.py
Labels: maintenance

#1443 Automatically repair configs broken by the last_error retry glitch
  music_assistant/server/controllers/config.py
Labels: bugfix

#1436 Don't load_provider if provider already deleted
  music_assistant/server/controllers/config.py
  music_assistant/server/server.py
Labels: bugfix

#1442 Snapcast: Reload built-in server in case of connection loss
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement

#1446 Fix some bugs caused by regression
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/spotify/__init__.py
Labels: bugfix

#1447 Reload Snapcast provider when connection to the server gets lost
  music_assistant/server/controllers/config.py
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement, bugfix

#1448 Better handle of SMB mount with special characters in username/password
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/filesystem_smb/__init__.py
Labels: bugfix

#1449 Add typing for radiobrowser
  music_assistant/server/controllers/cache.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/radiobrowser/__init__.py
  mypy.ini
Labels: ci, maintenance

#1451 A collection of small bugfixes and optimizations
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/config.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/dlna/helpers.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1452 Bump hass client to 1.2.0
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass/manifest.json
  requirements_all.txt
Labels: dependencies

#1455 Fix provider load at startup
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/server.py
Labels: bugfix

#1456 Use TaskManager instead of TaskGroup
  music_assistant/server/controllers/players.py
  music_assistant/server/helpers/multi_client_stream.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
Labels: enhancement

#1457 Apple Music: Ensure Albums have an artist for custom music.
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1459 Fix: Add guard for taskmanager aexit.
  music_assistant/server/helpers/util.py
Labels: bugfix

#1462 Apple Music: Fix albums without name, increase cooldown periode on 504 gateway timeouts.
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1463 Apple Music: Fix edge case for album parsing
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1467 Add file extension for log
  music_assistant/server/controllers/webserver.py
Labels: enhancement

#1450 Add typing for builtin
  music_assistant/server/providers/builtin/__init__.py
  mypy.ini
Labels: ci, maintenance

#1461 Add typing for filesystem_local
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  mypy.ini
Labels: ci, maintenance

#1468 Fix Jellyfin similar tracks
  music_assistant/server/providers/jellyfin/__init__.py
Labels: bugfix

#1469 Jellyfin: Skip tracks with no MediaStreams
  music_assistant/server/providers/jellyfin/__init__.py
Labels: bugfix

#1464 Subsonic: UNKNOWN_ARTIST handling
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: enhancement, bugfix

#1472 Cleanup Matching logic + add tests
  .vscode/launch.json
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  tests/server/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/server/test_compare.py
  tests/test_helpers.py
Labels: enhancement, bugfix, ci

#1470 Add type checking for filesystem_smb
  music_assistant/server/providers/filesystem_smb/__init__.py
  mypy.ini
Labels: ci, maintenance

#1474 Add typing for test provider
  music_assistant/server/providers/test/__init__.py
  mypy.ini
Labels: ci, maintenance

#1480 Refactor/cleanup the get/add logic for mediaitems + metadata retrieval
  music_assistant/client/music.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
Labels: enhancement, maintenance

#1479 Add typing for Plex
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/plex/helpers.py
  mypy.ini
Labels: ci, maintenance

#1481 frontend-2.6.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1482 Add typing for fullykiosk
  music_assistant/server/providers/fully_kiosk/__init__.py
  mypy.ini
Labels: ci, maintenance

#1485 Fix MusicBrainz external ID match
  music_assistant/common/helpers/util.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/const.py
  music_assistant/server/providers/jellyfin/parsers.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  tests/server/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/server/providers/jellyfin/test_parsers.py
  tests/server/test_compare.py
Labels: enhancement, bugfix

#1486 frontend-2.6.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1488 Revert ytmusicapi to 1.7.3
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix

#1489 Apple Music: (Hopefully) fix time out issues + fix handling of missing artist details
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1493 YT Music: Fix token expiration on reboot
  music_assistant/server/providers/ytmusic/__init__.py
Labels: bugfix

#1492 Update name to clarify difference with the integration
  Dockerfile
Labels: maintenance

#1491 Snapcast: Fix sync methods
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1495 frontend-2.6.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1496 Snapcast: Fix call _can_sync_with
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1497 YTMusic: Rewrite YTM auth to ytdlp access token plugin
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix

#1498 Apple Music: Fix playlist page size for Apple music.
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1500 frontend-2.6.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1505 YTMusic: Change to pypi package + dependency updates
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: enhancement

#1508 Fix AirPlay streams get mixed up when started in quick succession
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/builtin/__init__.py
Labels: enhancement, bugfix

#1510 frontend-2.7.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1509 Tidal PKCE login
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: breaking-change, enhancement, new-feature

#1520 Jellyfin: Fix artist enumeration
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: bugfix

#1511 Guard against eyed3 misread
  music_assistant/server/helpers/tags.py
Labels: bugfix

#1522 Typing: Add mypy for theaudiodb
  music_assistant/server/models/provider.py
  music_assistant/server/providers/theaudiodb/__init__.py
  mypy.ini
Labels: ci, maintenance

#1530 Add limit to tracks
  music_assistant/server/controllers/music.py
Labels: maintenance

#1521 Jellyfin: Use aiojellyfin 0.10.0 for stricter typing and more speed
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
  music_assistant/server/providers/jellyfin/manifest.json
  music_assistant/server/providers/jellyfin/parsers.py
  requirements_all.txt
  tests/server/providers/jellyfin/test_init.py
Labels: refactor, python

#1527 Add Japanese to locales
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1523 Subsonic: Add debug level logging around stream start, end, and details
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: maintenance

#1524 Spotify: remove deprecated user-read-birthdate scope
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement

#1526 Throttler: sleep without busy wait, log delayed calls
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement

#1536 Allow use of a personal client id for Spotify
  music_assistant/common/models/config_entries.py
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement

#1537 Prevent items get marked as unavailable during metadata scan
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/music.py
Labels: enhancement, bugfix
