Repository music-assistant/server, pull requests merged in 2024-04, with the labels that each got.

#1191 Soundcloudpy pip
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/soundcloud/manifest.json
  music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py
  pyproject.toml
  requirements_all.txt
Labels: dependencies, python

#1199 Fix sending announcements to playergroups/synced players
  music_assistant/common/models/player.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement, bugfix

#1202 Add videos to YTM search results
  music_assistant/server/providers/ytmusic/__init__.py
Labels: new-feature

#1203 Bugfixes and improvements to (universal) player groups
  music_assistant/common/helpers/uri.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/player.py
  music_assistant/constants.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/didl_lite.py
  music_assistant/server/helpers/multi_client_stream.py
  music_assistant/server/helpers/webserver.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/player.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
Labels: enhancement, refactor, bugfix

#1204 Tidal: Fix retrieval of images for media items
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: refactor, maintenance

#1206 Fix streaming of soundcloud
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/soundcloud/__init__.py
Labels: bugfix

#1208 Some optimizations to Airplay buffering
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
Labels: enhancement

#1207 Ensure favorited item is added to provider library
  music_assistant/server/controllers/music.py
Labels: bugfix

#1209 Announcements improvements
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/chromecast/__init__.py
Labels: enhancement, bugfix

#1215 Fix repeat when flow mode enabled
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
Labels: bugfix

#1216 Various fixes and code cleanup to the streaming logic
  music_assistant/common/helpers/util.py
  music_assistant/common/models/streamdetails.py
  music_assistant/constants.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/database.py
  music_assistant/server/helpers/process.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1214 Add support for using streamer provider publicly shareable URLs in search query
  music_assistant/common/helpers/uri.py
  music_assistant/common/models/errors.py
  music_assistant/constants.py
  music_assistant/server/controllers/music.py
Labels: new-feature

#1217 Add support to specify the Metadata language
  music_assistant/constants.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/helpers/webserver.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/providers/ytmusic/helpers.py
Labels: enhancement

#1218 Fix parse error in uri parser when track in name
  music_assistant/common/helpers/uri.py
Labels: bugfix

#1219 Some small fixes and enhancements to audio streaming
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/chromecast/helpers.py
Labels: enhancement, bugfix

#1221 Fix seeking in HLS streams (e.g. soundcloud)
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/soundcloud/__init__.py
Labels: enhancement, bugfix

#1222 Fix cleanup on removal of a provider
  music_assistant/common/helpers/uri.py
  music_assistant/server/controllers/music.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/server.py
Labels: bugfix

#1228 Add builtin Music provider
  music_assistant/client/client.py
  music_assistant/common/helpers/uri.py
  music_assistant/common/models/media_items.py
  music_assistant/common/models/provider.py
  music_assistant/constants.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/images.py
  music_assistant/server/helpers/resources/fallback_fanart.jpeg
  music_assistant/server/helpers/resources/logo.png
  music_assistant/server/helpers/tags.py
  music_assistant/server/models/metadata_provider.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/builtin/icon.svg
  music_assistant/server/providers/builtin/manifest.json
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
  music_assistant/server/providers/url/manifest.json
  music_assistant/server/providers/ytmusic/__init__.py
  tests/test_helpers.py
Labels: breaking-change, enhancement, new-provider, new-feature

#1229 frontend-2.4.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1233 Fix local artwork retrieval on filesystem providers
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
Labels: bugfix

#1232 A few small fixes and optimizations to playback
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement, bugfix

#1231 fix: Several minor fixes for deezer
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/gw_client.py
Labels: bugfix

#1234 Library and filesystem providers optimizations
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/providers/filesystem_local/base.py
Labels: enhancement, bugfix

#1235 frontend-2.4.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1236 frontend-2.4.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1230 429 backoff implementation
  music_assistant/common/models/errors.py
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: bugfix

#1238 Handle a few errors in the Jellyfin provider
  music_assistant/server/providers/jellyfin/__init__.py
Labels: bugfix

#1239 Some fixes for Db migration and startup
  music_assistant/server/controllers/music.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1240 Bugfixes and optimizations
  music_assistant/__main__.py
  music_assistant/client/music.py
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/media_items.py
  music_assistant/common/models/player.py
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/player.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1247 frontend-2.4.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1249 Handle missing album key in jellyfin playlist track
  music_assistant/server/providers/jellyfin/__init__.py
Labels: bugfix

#1250 Fix add to library on Tidal
  music_assistant/server/providers/tidal/__init__.py
Labels: bugfix

#1252 Do not load any providers by default (except builtin)
  music_assistant/server/controllers/config.py
  music_assistant/server/providers/airplay/manifest.json
  music_assistant/server/providers/builtin/manifest.json
  music_assistant/server/providers/chromecast/manifest.json
  music_assistant/server/providers/dlna/manifest.json
  music_assistant/server/providers/fanarttv/manifest.json
  music_assistant/server/providers/musicbrainz/manifest.json
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/theaudiodb/manifest.json
  music_assistant/server/providers/ugp/manifest.json
  music_assistant/server/server.py
Labels: enhancement

#1254 Optimize the database/library for large collections
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/database.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/builtin/manifest.json
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/test/__init__.py
  music_assistant/server/providers/test/icon.svg
  music_assistant/server/providers/test/manifest.json
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1262 Various small fixes and tweaks
  music_assistant/common/models/errors.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/database.py
  music_assistant/server/helpers/images.py
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1263 frontend-2.4.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release
