Repository music-assistant/server, pull requests merged in 2024-08, with the labels that each got.

#1539 Bump YTM dependencies + add url to provider mappings.
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: dependencies

#1540 Fix global cache key and YTMusic playlist edge case.
  music_assistant/server/controllers/music.py
  music_assistant/server/providers/ytmusic/helpers.py
Labels: bugfix

#1538 Ensure sort_name makes it to cache
  music_assistant/server/providers/filesystem_local/base.py
Labels: bugfix

#1546 YTMusic: Use instance name as playlist owner as fallback.
  music_assistant/server/providers/ytmusic/__init__.py
Labels: bugfix

#1541 Remove artist_id not album_id
  music_assistant/server/providers/filesystem_local/base.py
Labels: bugfix

#1549 Fix issue with track linking
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/compare.py
  tests/server/test_compare.py
Labels: bugfix

#1552 Improve metadata handling
  music_assistant/common/models/provider.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/compare.py
  music_assistant/server/providers/builtin/manifest.json
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/fanarttv/manifest.json
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/fully_kiosk/manifest.json
  music_assistant/server/providers/hass/manifest.json
  music_assistant/server/providers/hass_players/manifest.json
  music_assistant/server/providers/musicbrainz/manifest.json
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/snapcast/manifest.json
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/test/manifest.json
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/theaudiodb/manifest.json
  tests/server/providers/filesystem/__init__.py
  tests/server/providers/filesystem/test_helpers.py
Labels: enhancement

#1553 Improve metadata handling
  music_assistant/server/controllers/metadata.py
  music_assistant/server/helpers/api.py
Labels: enhancement

#1554 Fixes for global search
  music_assistant/client/music.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/music.py
Labels: enhancement, bugfix

#1555 Fix AirPlay playback gets mangled up between different streams
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/airplay/__init__.py
Labels: bugfix

#1556 Cleanup database from wrong matched info
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/database.py
Labels: bugfix, maintenance

#1557 frontend-2.8.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1562 Implement Spotify Connect Auth
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1563 frontend-2.8.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1566 Add demo/template providers
  DEVELOPMENT.md
  music_assistant/server/helpers/util.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/_template_music_provider/__init__.py
  music_assistant/server/providers/_template_music_provider/icon.svg
  music_assistant/server/providers/_template_music_provider/manifest.json
  music_assistant/server/providers/_template_player_provider/__init__.py
  music_assistant/server/providers/_template_player_provider/icon.svg
  music_assistant/server/providers/_template_player_provider/manifest.json
  music_assistant/server/server.py
Labels: enhancement, maintenance

#1567 Fix issues with items become unavailable
  music_assistant/client/client.py
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: enhancement, bugfix

#1568 Apple Music: Change log level to avoid chatty logs.
  music_assistant/server/providers/apple_music/__init__.py
Labels: enhancement

#1571 frontend-2.8.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1572 Various bugfixes and optimizations
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/playlists.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1574 Apple Music: Fix condition for hls substream optimization.
  music_assistant/server/helpers/audio.py
Labels: bugfix

#1575 Fix Spotify token gets invalidated every hour
  music_assistant/server/controllers/config.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fanarttv/__init__.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/server.py
Labels: bugfix

#1573 Change logger used for provider
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: enhancement

#1576 Remove the handle_async_init() call from provider __init__.py
  music_assistant/server/providers/opensubsonic/__init__.py
Labels: enhancement

#1577 Improve (local) metadata retrieval
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/models/core_controller.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_local/helpers.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/theaudiodb/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
  music_assistant/server/server.py
Labels: enhancement

#1583 Typo
  music_assistant/server/providers/musicbrainz/manifest.json
Labels: maintenance

#1582 frontend-2.8.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1584 Database (performance) enhancements
  .vscode/launch.json
  music_assistant/client/music.py
  music_assistant/common/models/enums.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/images.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
Labels: enhancement

#1585 frontend-2.8.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1586 Fix (album) images for track listings
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/tracks.py
Labels: bugfix

#1587 Fix (radio) browse listings
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/radiobrowser/__init__.py
Labels: bugfix

#1588 frontend-2.8.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1589 frontend-2.8.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1591 frontend-2.8.8
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1592 frontend-2.8.9
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1594 Fix removal of a provider
  music_assistant/server/controllers/media/base.py
Labels: bugfix

#1595 Fix Tidal login auth flow not showing
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
Labels: bugfix

#1596 Prevent db migration when upgrading from 2.1 to 2.2
  music_assistant/server/controllers/music.py
Labels: enhancement, bugfix

#1597 Small improvements to the spotify token auth
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1600 New Sonos S2 player provider
  .vscode/settings.json
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/sonos_s1/__init__.py
  music_assistant/server/providers/sonos_s1/helpers.py
  music_assistant/server/providers/sonos_s1/icon.png
  music_assistant/server/providers/sonos_s1/icon.svg
  music_assistant/server/providers/sonos_s1/manifest.json
  music_assistant/server/providers/sonos_s1/player.py
  music_assistant/server/providers/soundcloud/icon.svg
  music_assistant/server/providers/spotify/__init__.py
  requirements_all.txt
Labels: enhancement, new-provider

#1601 Jellyfin: Fix login for some instances
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: bugfix

#1602 A few minor follow-up fixes for the new Sonos provider
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/sonos_s1/player.py
  requirements_all.txt
Labels: enhancement, bugfix

#1603 A collection of small tweaks and bugfixes
  music_assistant/common/models/queue_item.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/media/radio.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/database.py
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/providers/filesystem_local/helpers.py
Labels: enhancement, bugfix

#1606 Add feature to transfer a queue
  music_assistant/client/player_queues.py
  music_assistant/constants.py
  music_assistant/server/controllers/player_queues.py
Labels: new-feature

#1607 Add config option to specify the http content length header
  music_assistant/common/models/config_entries.py
  music_assistant/constants.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement

#1608 Sonos S2 provider follow-up
  music_assistant/server/providers/sonos/__init__.py
Labels: enhancement

#1609 frontend-2.8.10
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1610 Fix playback of radio streams on Sonos S2 provider
  music_assistant/server/providers/sonos/__init__.py
Labels: bugfix

#1611 Enforce default HTTP profile for slimproto players
  music_assistant/common/models/config_entries.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: bugfix

#1612 More bugfixes for the new Sonos provider
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/manifest.json
  requirements_all.txt
Labels: enhancement, bugfix

#1613 Some more tweaks/fixes to the Sonos S2 provider
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/sonos_s1/__init__.py
  requirements_all.txt
Labels: enhancement, bugfix

#1620 frontend-2.8.11
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1525 Typing: Tidal
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
  mypy.ini
Labels: ci, maintenance

#1621 Fixes and enhancements to syncgroups and UGP groups
  music_assistant/common/models/player.py
  music_assistant/constants.py
  music_assistant/server/controllers/players.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/slimproto/multi_client_stream.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement, bugfix

#1622 Some fixes for unstable (HLS) radio streams
  music_assistant/constants.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
Labels: bugfix

#1625 Filesystem matching and metadata fixes
  music_assistant/server/controllers/metadata.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_local/helpers.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  tests/server/providers/filesystem/test_helpers.py
Labels: enhancement, bugfix, maintenance

#1626 Fix snapcast state not updating
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1623 Add Korean to supported languages
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1627 Fix a typo
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1630 Fix playback of HTTP sources
  music_assistant/server/helpers/audio.py
Labels: bugfix

#1633 Introduce a HLS radio streams parser (for the BBC radio streams)
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
Labels: new-feature

#1632 Add dev manual build
  .github/workflows/release.yml
  Dockerfile
Labels: ci
