Repository music-assistant/server, pull requests merged in 2024-03, with the labels that each got.

#1130 A collection of small enhancements
  .github/release-drafter.yml
  .github/workflows/pr-labels.yaml
  music_assistant/common/models/config_entries.py
  music_assistant/constants.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement

#1131 A lot of optimizations to the SlimProto provider
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/media_items.py
  music_assistant/constants.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/slimproto/cli.py
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/slimproto/models.py
  requirements_all.txt
Labels: enhancement, bugfix, maintenance

#1135 Small fixes
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
Labels: bugfix, maintenance

#1137 Subsonic: Check for transcodeOffset support on startup
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#1139 Fix volume normalization
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/media_items.py
  music_assistant/common/models/player_queue.py
  music_assistant/common/models/queue_item.py
  music_assistant/common/models/streamdetails.py
  music_assistant/constants.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/process.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/deezer/gw_client.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: enhancement, bugfix, maintenance

#1144 Group playback fixes
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/didl_lite.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement, bugfix

#1145 YTMusic fixes
  music_assistant/server/providers/slimproto/manifest.json
  music_assistant/server/providers/ytmusic/__init__.py
Labels: enhancement, bugfix

#1147 Fix playback issues on Qobuz
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/qobuz/__init__.py
Labels: bugfix

#1148 Announce support (TTS with automatic resume)
  .gitignore
  music_assistant/client/players.py
  music_assistant/common/helpers/global_cache.py
  music_assistant/common/helpers/uri.py
  music_assistant/common/helpers/util.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/player.py
  music_assistant/common/models/player_queue.py
  music_assistant/common/models/queue_item.py
  music_assistant/common/models/streamdetails.py
  music_assistant/constants.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
Labels: new-feature

#1149 Fix playback on Universal Group and Snapcast
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: bugfix

#1150 Include a Snapserver in the snapcast provider
  music_assistant/common/helpers/util.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/snapcast/__init__.py
Labels: new-feature

#1151 A few small fixes
  music_assistant/server/controllers/streams.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/spotify/__init__.py
Labels: enhancement, bugfix

#1154 Use Deezer artist name instead of ID when ID isn't present
  music_assistant/server/providers/deezer/__init__.py
Labels: bugfix

#1156 Performance and stability improvements to streaming
  music_assistant/__main__.py
  music_assistant/client/client.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/auth.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/snapcast/manifest.json
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
  requirements_all.txt
Labels: enhancement, bugfix

#1155 Jellyfin Transcoding Fix
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
Labels: bugfix

#1157 Fix high memory and cpu usage from analyze jobs
  music_assistant/server/helpers/audio.py
Labels: bugfix

#1159 Some fixes for Announcement feature
  music_assistant/constants.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement, bugfix

#1162 Flow stream enhancements
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/didl_lite.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/server.py
Labels: enhancement

#1163 Fix default Snapserver config
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/snapcast/snapweb/apple-touch-icon-180x180.png
  music_assistant/server/providers/snapcast/snapweb/assets/10-seconds-of-silence-j39Pm5R-.mp3
  music_assistant/server/providers/snapcast/snapweb/assets/index-BDBx6C_I.css
  music_assistant/server/providers/snapcast/snapweb/assets/index-DDLZhQdU.js
  music_assistant/server/providers/snapcast/snapweb/assets/logo192-wKJb_L8G.png
  music_assistant/server/providers/snapcast/snapweb/assets/snapcast-512-B1PzHP_P.png
  music_assistant/server/providers/snapcast/snapweb/favicon.ico
  music_assistant/server/providers/snapcast/snapweb/index.html
  music_assistant/server/providers/snapcast/snapweb/logo.svg
  music_assistant/server/providers/snapcast/snapweb/manifest.webmanifest
  music_assistant/server/providers/snapcast/snapweb/maskable-icon-512x512.png
  music_assistant/server/providers/snapcast/snapweb/pwa-192x192.png
  music_assistant/server/providers/snapcast/snapweb/pwa-512x512.png
  music_assistant/server/providers/snapcast/snapweb/pwa-64x64.png
  music_assistant/server/providers/snapcast/snapweb/registerSW.js
  music_assistant/server/providers/snapcast/snapweb/robots.txt
  music_assistant/server/providers/snapcast/snapweb/sw.js
  music_assistant/server/providers/snapcast/snapweb/workbox-3e911b1d.js
  pyproject.toml
Labels: enhancement

#1164 Fix typo in config controller
  music_assistant/server/controllers/config.py
Labels: bugfix

#1166 Fix cleanup of (aborted) ffmpeg processes
  music_assistant/__main__.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement, bugfix

#1160 Add support for Dev Containers/Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  DEVELOPMENT.md
Labels: dependencies, maintenance

#1167 Several improvements to playing radio streams
  music_assistant/common/models/enums.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/playlists.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
Labels: enhancement, bugfix

#1161 Add support for Spotify Liked Songs
  music_assistant/server/providers/spotify/__init__.py
Labels: new-feature

#1168 Add small buffer in Airplay streaming logic
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
Labels: enhancement, bugfix

#1169 Fix install packages using pip
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/util.py
  music_assistant/server/providers/opensubsonic/manifest.json
  requirements_all.txt
Labels: bugfix

#1170 Prevent stderr pipe buffer overflow on long running radio streams
  music_assistant/server/helpers/process.py
Labels: bugfix

#1165 Tidal-api-0.7.5
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
  music_assistant/server/providers/tidal/manifest.json
  requirements_all.txt
Labels: dependencies

#1171 [Deezer]: Update deezer-python-async to use pypi version
  music_assistant/server/providers/deezer/manifest.json
  requirements_all.txt
Labels: dependencies

#1172 Increase Airplay playback buffer
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/process.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement

#1173 Implement a safer way to deal with the buffer limit
  music_assistant/server/helpers/process.py
Labels: enhancement, bugfix

#1174 Various fixes for Tidal
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: bugfix

#1181 frontend-2.3.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1182 Fixes for logging
  docker-compose.example.yml
  music_assistant/__main__.py
  music_assistant/constants.py
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/models/core_controller.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/tidal/helpers.py
  music_assistant/server/server.py
Labels: enhancement, bugfix

#1184 Some enhancements to the Announcement feature
  music_assistant/client/players.py
  music_assistant/common/models/config_entries.py
  music_assistant/constants.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
Labels: enhancement, bugfix

#1185 Add categories to config entries
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/player.py
  music_assistant/constants.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/ugp/__init__.py
Labels: enhancement

#1186 frontend-2.4.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1187 Several tweaks for radio streams and YTM
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: enhancement, bugfix

#1188 Fix streaming issues with YouTube Music
  music_assistant/common/models/enums.py
  music_assistant/common/models/streamdetails.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tunein/__init__.py
  music_assistant/server/providers/url/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: bugfix

#1189 More fixes for playback and better logging
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tunein/__init__.py
Labels: bugfix

#1190 frontend-2.4.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release
