Repository music-assistant/server, pull requests merged in 2024-06, with the labels that each got.

#1323 Fix cleanup of orphaned artists and albums on local file provider
  music_assistant/server/providers/filesystem_local/base.py
Labels: bugfix

#1330 Fix: apple music playlists
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1313 Add Plex Connect Locally
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/plex/helpers.py
Labels: new-feature

#1325 Make Jellyfin provider compatible with Emby
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
  music_assistant/server/providers/jellyfin/icon.svg
Labels: enhancement

#1335 Two updates to the Subsonic provider
  music_assistant/common/models/errors.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: new-feature

#1337 frontend-2.5.11
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1336 Several small bugfixes
  music_assistant/common/models/config_entries.py
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/tunein/__init__.py
Labels: bugfix

#1338 Jellyfin: Don't fail entire sync if a single track or album have an invalid mbid
  music_assistant/server/providers/jellyfin/__init__.py
Labels: bugfix

#1324 Refactor SnapCastProvider cmd_volume_set method
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1347 Fix snapcast player unsync when master off
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1348 Several small bugfixes
  music_assistant/common/models/config_entries.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/server/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/server/providers/airplay/bin/cliraop-macos-arm64
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
Labels: enhancement, bugfix

#1349 frontend-2.5.12
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1351 Apple Music: Fixed lots of metadata related issues
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1355 Playback/enqueue fixes
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/fully_kiosk/__init__.py
Labels: bugfix

#1358 frontend-2.5.13
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1360 Fix snapcast group child
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1361 Fix race condition causing a (potential) endless loop
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
Labels: bugfix

#1363 Snapcast add guard for sync_many on cmd_sync
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1364 Auto retry provider load if its unavailable or the connection gets lost
  music_assistant/server/controllers/config.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass/manifest.json
  music_assistant/server/providers/hass_players/__init__.py
  music_assistant/server/server.py
  requirements_all.txt
Labels: enhancement, bugfix

#1365 Fixed volume fixes
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/sonos/__init__.py
Labels: bugfix

#1366 frontend-2.5.14
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1362 Jellyfin: Drop all synchronous HTTP and use aiohttp instread
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: enhancement

#1368 Fix a typing issue in the client.
  music_assistant/client/client.py
Labels: bugfix

#1371 Jellyfin: Typing improvements
  music_assistant/common/models/enums.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: enhancement

#1381 Add index on timestamp_added
  music_assistant/server/controllers/music.py
Labels: enhancement

#1388 Prevent overwriting album_tracks table
  music_assistant/server/controllers/media/tracks.py
Labels: enhancement, bugfix

#1389 Improve library performance
  music_assistant/constants.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/tracks.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/database.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
Labels: enhancement, maintenance

#1383 Jellyfin: Faster track fetching
  music_assistant/constants.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
Labels: enhancement

#1390 Jellyfin: Stricter typing
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: enhancement, refactor

#1391 frontend-2.5.15
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1392 A collection of small bugfixes and tweaks
  music_assistant/common/models/config_entries.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/multi_client_stream.py
  music_assistant/server/helpers/tags.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_local/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/hass/__init__.py
  music_assistant/server/providers/hass/manifest.json
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/server.py
  requirements_all.txt
Labels: enhancement, bugfix

#1385 Snapcast fix sync and unsync many
  music_assistant/server/models/player_provider.py
Labels: enhancement

#1394 Update Locales
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1395 Snapcast: re-add update all clients on sync and unsync
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1398 Tests: Add a 'mass' fixture
  music_assistant/server/server.py
  tests/conftest.py
  tests/server/__init__.py
  tests/server/test_server.py
Labels: ci, maintenance

#1397 Jellyfin: Add some basic parsing tests
  .github/workflows/test.yml
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/parsers.py
  pyproject.toml
  tests/server/providers/jellyfin/__init__.py
  tests/server/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/server/providers/jellyfin/fixtures/albums/this_is_christmas.json
  tests/server/providers/jellyfin/fixtures/albums/yesterday_when_i_was_mad.json
  tests/server/providers/jellyfin/fixtures/artists/ash.json
  tests/server/providers/jellyfin/fixtures/tracks/thrown_away.json
  tests/server/providers/jellyfin/fixtures/tracks/where_the_bands_are.json
  tests/server/providers/jellyfin/fixtures/tracks/zombie_christmas.json
  tests/server/providers/jellyfin/test_parsers.py
Labels: ci, maintenance

#1399 Snapcast add config built in server
  music_assistant/server/providers/snapcast/__init__.py
Labels: enhancement

#1402 Fix playback for video based songs without artist info.
  music_assistant/server/providers/ytmusic/helpers.py
Labels: bugfix

#1401 Fix radio for playlists < 5 items.
  music_assistant/server/controllers/media/playlists.py
Labels: bugfix

#1387 Switch from unmaintained pytube to yt-dlp. Check user is subscribed to YTM premium
  music_assistant/server/providers/ytmusic/__init__.py
  music_assistant/server/providers/ytmusic/helpers.py
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: enhancement

#1420 Some Typos in locales
  music_assistant/server/controllers/metadata.py
Labels: maintenance

#1423 Snapcast fix sync to
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1415 Fix unload on snapcast
  music_assistant/server/providers/snapcast/__init__.py
Labels: maintenance

#1403 Jellyfin: Add more test scaffolding.
  music_assistant/server/providers/jellyfin/manifest.json
  requirements_all.txt
  tests/common.py
  tests/conftest.py
  tests/server/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/server/providers/jellyfin/fixtures/albums/infest.json
  tests/server/providers/jellyfin/test_init.py
Labels: ci, maintenance

#1412 Avoid subshells when using check_output
  music_assistant/server/helpers/audio.py
  music_assistant/server/providers/airplay/__init__.py
  music_assistant/server/providers/filesystem_smb/__init__.py
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#1416 Mypy: Get mypy passing on music_assistant.client
  music_assistant/client/client.py
  music_assistant/client/config.py
  music_assistant/client/connection.py
  music_assistant/client/music.py
  music_assistant/client/player_queues.py
  music_assistant/client/players.py
  music_assistant/common/models/api.py
Labels: ci, maintenance

#1425 Apple Music: Fix tracks that are unavailable in the catalog + Fix tracks with no album data
  music_assistant/server/providers/apple_music/__init__.py
Labels: bugfix

#1411 Double check external ID comparison
  music_assistant/server/controllers/media/base.py
Labels: enhancement, bugfix

#1414 Jellyfin: add similar tracks
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/manifest.json
  pyproject.toml
  requirements_all.txt
Labels: enhancement

#1413 Run mypy on CI
  .pre-commit-config.yaml
  music_assistant/server/helpers/tags.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/manifest.json
  music_assistant/server/providers/jellyfin/parsers.py
  mypy.ini
  requirements_all.txt
  tests/test_tags.py
Labels: ci, maintenance

#1427 Carefully handle redirect from players to queue controller
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
Labels: enhancement, bugfix
