Repository music-assistant/server, pull requests merged in 2024-05, with the labels that each got.

#1264 Open Subsonic: Fix MediaImageItem constructor call
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#1266 Mark item played on Plex after playback finishes
  music_assistant/server/providers/plex/__init__.py
Labels: bugfix

#1269 frontend-2.5.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1267 Fix: Sanitize radio stream title
  music_assistant/common/helpers/util.py
  music_assistant/server/helpers/audio.py
  tests/test_radio_stream_title.py
Labels: bugfix

#1270 frontend-2.5.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1253 Better handling of Jellyfin metadata missing
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/jellyfin/const.py
Labels: bugfix

#1278 Make client library feature complete
  music_assistant/client/client.py
  music_assistant/client/config.py
  music_assistant/client/music.py
  music_assistant/client/player_queues.py
  music_assistant/client/players.py
  music_assistant/common/models/api.py
  music_assistant/common/models/enums.py
  music_assistant/common/models/media_items.py
  music_assistant/common/models/provider.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/metadata.py
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/webserver.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/models/provider.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/ytmusic/__init__.py
  scripts/example.py
Labels: breaking-change, enhancement, bugfix, maintenance

#1279 Various small bugfixes and enhancements
  music_assistant/server/controllers/music.py
  music_assistant/server/controllers/players.py
  music_assistant/server/helpers/process.py
  music_assistant/server/helpers/webserver.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/deezer/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
  music_assistant/server/providers/soundcloud/__init__.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
  music_assistant/server/providers/ytmusic/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: bugfix, maintenance

#1280 frontend-2.5.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1281 Fix: Deezer albums
  music_assistant/server/providers/deezer/__init__.py
Labels: bugfix, python

#1282 Fix call to _get_provider_playlist_tracks
  music_assistant/server/controllers/media/playlists.py
Labels: bugfix

#1283 Fix several issues with playlists edits
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/spotify/__init__.py
  music_assistant/server/providers/tidal/__init__.py
  music_assistant/server/providers/tidal/helpers.py
Labels: enhancement, bugfix

#1284 frontend-2.5.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1286 frontend-2.5.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1288 frontend-2.5.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1290 Fix phantom artists in library
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/artists.py
Labels: bugfix

#1291 Fix default enqueue options
  music_assistant/server/controllers/player_queues.py
Labels: bugfix

#1292 frontend-2.5.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1293 Fix mass user playlists (and queue items) limited to 50 items
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/playlists.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/filesystem_local/base.py
Labels: bugfix

#1294 frontend-2.5.8
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1301 A collection of small bugfixes
  music_assistant/server/helpers/tags.py
  music_assistant/server/helpers/throttle_retry.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/builtin/manifest.json
  music_assistant/server/providers/qobuz/__init__.py
Labels: bugfix

#1302 Do not use ISRC or barcode for lookups on MusicBrainz
  music_assistant/server/providers/musicbrainz/__init__.py
Labels: enhancement, bugfix

#1303 Remove Requirement for Password for Jellyfin
  music_assistant/server/providers/jellyfin/__init__.py
Labels: enhancement, bugfix

#1305 A collection of small bugfixes and tweaks
  music_assistant/common/models/media_items.py
  music_assistant/server/controllers/media/albums.py
  music_assistant/server/controllers/media/artists.py
  music_assistant/server/controllers/media/base.py
  music_assistant/server/controllers/music.py
  music_assistant/server/models/music_provider.py
  music_assistant/server/providers/builtin/__init__.py
  music_assistant/server/providers/jellyfin/__init__.py
  music_assistant/server/providers/radiobrowser/__init__.py
Labels: bugfix

#1306 frontend-2.5.9
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1307 frontend-2.5.10
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1309 Fix add to Tidal Library
  music_assistant/server/providers/tidal/helpers.py
Labels: bugfix

#1310 Adjust release script to account for both beta and stable releases
  .github/workflows/release.yml
Labels: dependencies, ci, github_actions

#1312 Fix typo in sample rate config options
  music_assistant/common/models/config_entries.py
Labels: bugfix, maintenance

#1315 Apple music provider
  .github/workflows/release.yml
  Dockerfile
  music_assistant/common/models/enums.py
  music_assistant/common/models/streamdetails.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/helpers/app_vars.py
  music_assistant/server/helpers/audio.py
  music_assistant/server/helpers/playlists.py
  music_assistant/server/providers/apple_music/__init__.py
  music_assistant/server/providers/apple_music/bin/README.md
  music_assistant/server/providers/apple_music/icon.svg
  music_assistant/server/providers/apple_music/manifest.json
  requirements_all.txt
Labels: new-provider

#1318 Turn off Display and visualization by default
  music_assistant/server/providers/slimproto/__init__.py
Labels: bugfix

#1322 Fix snapcast players ids
  music_assistant/server/providers/snapcast/__init__.py
  music_assistant/server/providers/snapcast/manifest.json
  requirements_all.txt
Labels: bugfix
