Repository music-assistant/server, pull requests merged in 2024-01, with the labels that each got.

#991 Fixes bug where sanpcast does not work
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix

#995 Add guard for missing id in MusicBrainz result
  music_assistant/server/providers/musicbrainz/__init__.py
Labels: bugfix

#996 frontend-2.0.17
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#997 Reverting a change in the ytmusicapi that currently breaks YTMusic.
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix

#999 Some small bug fixes
  music_assistant/server/controllers/config.py
  music_assistant/server/providers/filesystem_local/base.py
  music_assistant/server/providers/musicbrainz/__init__.py
  music_assistant/server/providers/qobuz/__init__.py
Labels: bugfix

#1000 Fixes for plex connection
  music_assistant/server/providers/plex/__init__.py
  music_assistant/server/providers/plex/helpers.py
  music_assistant/server/providers/plex/manifest.json
  requirements_all.txt
Labels: breaking-change, refactor

#1013 frontend-2.1.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1006 Add Open Subsonic MusicProvider
  music_assistant/server/providers/opensubsonic/__init__.py
  music_assistant/server/providers/opensubsonic/icon.svg
  music_assistant/server/providers/opensubsonic/manifest.json
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  requirements_all.txt
Labels: new-provider

#1015 Replace UUID check on MusicBrainz ID
  music_assistant/common/helpers/util.py
  music_assistant/common/models/media_items.py
Labels: bugfix

#1016 Fix next track playback on Chromecast groups
  music_assistant/server/providers/chromecast/__init__.py
Labels: bugfix

#1022 Youtube maintenance
  music_assistant/server/providers/ytmusic/helpers.py
  music_assistant/server/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix, maintenance

#1023 Remove python-ffmpeg requirement from Snapcast manifest.json
  music_assistant/server/providers/snapcast/manifest.json
  requirements_all.txt
Labels: maintenance

#1025 A few small improvements to the Chromecast provider
  music_assistant/constants.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/chromecast/__init__.py
Labels: maintenance

#1026 Fix musicbrainz id check
  music_assistant/common/helpers/util.py
Labels: bugfix

#1027 Some fixes to the Subsonic provider
  music_assistant/server/providers/opensubsonic/manifest.json
  music_assistant/server/providers/opensubsonic/sonic_provider.py
  requirements_all.txt
Labels: bugfix

#1028 Subsonic: Handle missing artist id and check before building Images
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#1029 Fix queue track repeat + Some improvements to Sonos players
  music_assistant/common/models/player_queue.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/models/player_provider.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/sonos/__init__.py
Labels: bugfix, maintenance

#1030 A collection of small fixes and enhancements
  music_assistant/common/models/config_entries.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/chromecast/__init__.py
  music_assistant/server/providers/dlna/__init__.py
  music_assistant/server/providers/sonos/__init__.py
Labels: bugfix, maintenance

#1032 Add player provider for devices running fully kiosk
  music_assistant/server/providers/fully_kiosk/__init__.py
  music_assistant/server/providers/fully_kiosk/manifest.json
  requirements_all.txt
Labels: new-provider

#1033 Add default enqueue options
  music_assistant/client/players.py
  music_assistant/server/controllers/player_queues.py
Labels: maintenance

#1034 frontend-2.1.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1035 Subsonic: Better scrobbling and track enumeration
  music_assistant/server/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#1038 Fix Sonos player provider
  music_assistant/common/models/player.py
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/players.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/helpers.py
  music_assistant/server/providers/sonos/manifest.json
  music_assistant/server/providers/sonos/player.py
  music_assistant/server/providers/ugp/__init__.py
  music_assistant/server/server.py
  requirements_all.txt
Labels: bugfix, maintenance

#1039 Some small bugfixes and optimizations
  music_assistant/server/controllers/player_queues.py
  music_assistant/server/controllers/players.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/player.py
Labels: bugfix, maintenance

#1040 frontend-2.1.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1044 Bugfixes for corrupted Sonos player configs and slimproto sync
  music_assistant/server/controllers/config.py
  music_assistant/server/controllers/streams.py
  music_assistant/server/providers/slimproto/__init__.py
  music_assistant/server/providers/sonos/__init__.py
  music_assistant/server/providers/sonos/player.py
Labels: bugfix, maintenance

#1045 Speed-up startup and fix clear cache
  music_assistant/server/controllers/cache.py
  music_assistant/server/controllers/music.py
  music_assistant/server/helpers/database.py
Labels: maintenance

#1053 Replace None with empty string where necessary
  music_assistant/server/providers/tidal/__init__.py
Labels: bugfix

#1054 Fix async issue in SnapcastProvider
  music_assistant/server/providers/snapcast/__init__.py
Labels: bugfix
