Repository music-assistant/server, pull requests merged in 2025-03, with the labels that each got.

#1981 Feat: Move the output limiter option from DSP to Player Settings
  music_assistant/constants.py
  music_assistant/controllers/config.py
  music_assistant/helpers/audio.py
Labels: enhancement

#1994 ABS: fix for another unexpected API response
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/manifest.json
  music_assistant/providers/audiobookshelf/parsers.py
  requirements_all.txt
Labels: bugfix

#1977 Add iTunes Podcast Search Provider
  music_assistant/providers/itunes_podcasts/README.md
  music_assistant/providers/itunes_podcasts/__init__.py
  music_assistant/providers/itunes_podcasts/itunes_country_codes.json
  music_assistant/providers/itunes_podcasts/manifest.json
  music_assistant/providers/itunes_podcasts/parsers.py
  music_assistant/providers/itunes_podcasts/schema.py
  pyproject.toml
Labels: new-provider

#1982 Audible provider: Fixes pagination and small cleanups
  music_assistant/providers/audible/__init__.py
  music_assistant/providers/audible/audible_helper.py
Labels: enhancement, bugfix

#2001 frontend-2.12.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2002 frontend-2.12.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1995 Adjust Tidal provider to a fully async implementation
  music_assistant/helpers/app_vars.py
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/auth_manager.py
  music_assistant/providers/tidal/helpers.py
  music_assistant/providers/tidal/manifest.json
  requirements_all.txt
Labels: enhancement, refactor

#2003 Various bugfixes for the Tidal provider after the refactor
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/auth_manager.py
Labels: bugfix

#2004 Tidal: remove unnecessary error handling decorator
  music_assistant/providers/tidal/__init__.py
Labels: bugfix

#2005 Tidal: replace generic exceptions with specifics
  music_assistant/providers/tidal/__init__.py
Labels: enhancement

#1850 Add LastFM Audio Scrobbler plugin provider
  music_assistant/providers/lastfm_scrobble/__init__.py
  music_assistant/providers/lastfm_scrobble/icon.svg
  music_assistant/providers/lastfm_scrobble/manifest.json
  requirements_all.txt
Labels: new-provider

#2007 Fix: Missing `MULTI_DEVICE_DSP` in player groups
  music_assistant/providers/player_group/__init__.py
Labels: bugfix

#1988 Add advanced networking (list of IPs) to Sonos S1 provider
  music_assistant/providers/sonos_s1/__init__.py
Labels: enhancement

#2010 Tidal provider maintenance: add tidaluser class
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/auth_manager.py
Labels: enhancement

#2013 Add pkce to Tidal provider's manifest requirements
  music_assistant/providers/tidal/manifest.json
Labels: bugfix

#2008 Add ListenBrainz scrobbler provider
  music_assistant/providers/listenbrainz_scrobble/__init__.py
  music_assistant/providers/listenbrainz_scrobble/icon.svg
  music_assistant/providers/listenbrainz_scrobble/manifest.json
  requirements_all.txt
Labels: new-provider

#2015 Rename the slimproto provider to squeezelite
  music_assistant/controllers/config.py
  music_assistant/providers/slimproto/manifest.json
  music_assistant/providers/squeezelite/__init__.py
  music_assistant/providers/squeezelite/icon.svg
  music_assistant/providers/squeezelite/icon_monochrome.svg
  music_assistant/providers/squeezelite/manifest.json
  music_assistant/providers/squeezelite/multi_client_stream.py
  pyproject.toml
Labels: maintenance

#2009 Feat: Built-in Web Player Provider
  music_assistant/controllers/webserver.py
  music_assistant/helpers/webserver.py
  music_assistant/providers/builtin_player/__init__.py
  music_assistant/providers/builtin_player/icon.svg
  music_assistant/providers/builtin_player/icon_monochrome.svg
  music_assistant/providers/builtin_player/manifest.json
  pyproject.toml
  requirements_all.txt
Labels: new-provider

#2012 Fix: Subsonic: Catch DataNotFoundError for artwork
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#2016 frontend-2.13.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2017 Ignore playlists which are stored with album tracks
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/filesystem_local/constants.py
  music_assistant/providers/filesystem_smb/__init__.py
Labels: enhancement

#2019 Fix playlist parsing with parent folder references
  music_assistant/providers/filesystem_local/__init__.py
Labels: bugfix

#2018 Various bugfixes for the LastFM provider
  music_assistant/providers/lastfm_scrobble/__init__.py
Labels: bugfix

#2025 frontend-2.13.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2026 Increase clarity of note
  music_assistant/providers/filesystem_local/constants.py
Labels: maintenance

#2028 [LastFM Scrobbler] Add some basic unit tests and fix a bug
  music_assistant/providers/lastfm_scrobble/__init__.py
  tests/providers/lastfm_scrobble/__init__.py
  tests/providers/lastfm_scrobble/test_events.py
Labels: enhancement, bugfix

#2032 Some small improvements to the Airplay provider
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/airplay/raop.py
Labels: enhancement

#2033 Add base logic for recommendations
  .vscode/settings.json
  music_assistant/controllers/music.py
  music_assistant/models/music_provider.py
  music_assistant/providers/_template_music_provider/__init__.py
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/radiobrowser/__init__.py
  pyproject.toml
  requirements_all.txt
  tests/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
Labels: new-feature

#2034 [Chore] Move podcastparser parse functions from itunes search provider to helpers
  music_assistant/helpers/podcast_parsers.py
  music_assistant/providers/itunes_podcasts/__init__.py
  music_assistant/providers/itunes_podcasts/manifest.json
Labels: maintenance

#2031 Feat: Mutichannel Parametric Equalizer
  music_assistant/helpers/dsp.py
Labels: new-feature

#2037 Several optimizations to the Snapcast provider
  music_assistant/helpers/ffmpeg.py
  music_assistant/helpers/process.py
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/snapcast/control.py
  music_assistant/providers/snapcast/manifest.json
  music_assistant/providers/snapcast/snapweb/apple-touch-icon-180x180.png
  music_assistant/providers/snapcast/snapweb/assets/10-seconds-of-silence-j39Pm5R-.mp3
  music_assistant/providers/snapcast/snapweb/assets/index-BDBx6C_I.css
  music_assistant/providers/snapcast/snapweb/assets/index-BYMjFABP.js
  music_assistant/providers/snapcast/snapweb/assets/logo192-wKJb_L8G.png
  music_assistant/providers/snapcast/snapweb/assets/snapcast-512-B1PzHP_P.png
  music_assistant/providers/snapcast/snapweb/favicon.ico
  music_assistant/providers/snapcast/snapweb/index.html
  music_assistant/providers/snapcast/snapweb/logo.svg
  music_assistant/providers/snapcast/snapweb/manifest.webmanifest
  music_assistant/providers/snapcast/snapweb/maskable-icon-512x512.png
  music_assistant/providers/snapcast/snapweb/pwa-192x192.png
  music_assistant/providers/snapcast/snapweb/pwa-512x512.png
  music_assistant/providers/snapcast/snapweb/pwa-64x64.png
  music_assistant/providers/snapcast/snapweb/registerSW.js
  music_assistant/providers/snapcast/snapweb/robots.txt
  music_assistant/providers/snapcast/snapweb/sw.js
  music_assistant/providers/snapcast/snapweb/workbox-3e911b1d.js
  requirements_all.txt
Labels: new-feature, maintenance

#2035 Podcastfeed: Use helper functions
  music_assistant/providers/podcastfeed/__init__.py
  music_assistant/providers/podcastfeed/manifest.json
  pyproject.toml
Labels: maintenance

#2038 frontend-2.14.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2036 Add gPodder podcast provider
  music_assistant/providers/gpodder/README.md
  music_assistant/providers/gpodder/__init__.py
  music_assistant/providers/gpodder/client.py
  music_assistant/providers/gpodder/icon.svg
  music_assistant/providers/gpodder/manifest.json
Labels: new-provider

#2041 abs - fix: do not sync audiobooks without tracks
  music_assistant/providers/audiobookshelf/__init__.py
Labels: bugfix

#2040 Add Recommendations to Tidal provider
  music_assistant/constants.py
  music_assistant/controllers/music.py
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/auth_manager.py
  music_assistant/providers/tidal/tidal_page_parser.py
Labels: new-feature

#2042 Refactor common code from listenbrainz and lastfm scrobblers
  music_assistant/helpers/__init__.py
  music_assistant/helpers/scrobbler.py
  music_assistant/providers/lastfm_scrobble/__init__.py
  music_assistant/providers/listenbrainz_scrobble/__init__.py
  tests/core/test_scrobbler.py
Labels: enhancement, maintenance

#2044 Fix snapcast using external snapserver
  music_assistant/providers/snapcast/__init__.py
Labels: bugfix

#2043 feat: Built-in Web Player Part 2
  music_assistant/providers/builtin_player/__init__.py
Labels: enhancement

#2050 Ignore GVS token message for now.
  music_assistant/providers/ytmusic/__init__.py
Labels: bugfix

#2049 Tidal: lower cache ttl, add translation keys to folders
  music_assistant/providers/tidal/__init__.py
Labels: refactor

#2053 fix: gPodder not checking guid on playlog sync if it is present
  music_assistant/providers/gpodder/__init__.py
Labels: bugfix

#2052 Make airplay provider robust to empty dacp request
  music_assistant/providers/airplay/provider.py
Labels: bugfix

#2048 Add artist and release mbids to listenbrainz scobbles
  music_assistant/controllers/player_queues.py
  music_assistant/providers/audiobookshelf/parsers.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/listenbrainz_scrobble/__init__.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  music_assistant/providers/test/__init__.py
  pyproject.toml
  requirements_all.txt
  tests/core/test_scrobbler.py
Labels: enhancement

#2065 frontend-2.13.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2067 Subsonic: Set metadata.release_date when available
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: enhancement

#2063 Soundcloud: Fallback to the track details for missing entries in playlists
  music_assistant/providers/soundcloud/__init__.py
Labels: bugfix

#2068 frontend-2.14.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2069 YT Music: Auto generate PO tokens for stream urls
  music_assistant/providers/ytmusic/__init__.py
  music_assistant/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix

#2071 Tidal: fix images and add descriptions to mixes
  music_assistant/providers/tidal/__init__.py
Labels: enhancement

#2072 fix: Built-in Web Player Part 3
  music_assistant/providers/builtin_player/__init__.py
Labels: enhancement, bugfix

#2073 frontend-2.14.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2074 ABS: Enhancement - support for recommendations
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/constants.py
  music_assistant/providers/audiobookshelf/parsers.py
Labels: enhancement

#2076 Add recommendations to itunes_podcasts
  music_assistant/helpers/podcast_parsers.py
  music_assistant/providers/itunes_podcasts/__init__.py
  music_assistant/providers/itunes_podcasts/schema.py
Labels: enhancement

#2077 frontend-2.14.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2080 abs: browse recommendation
  music_assistant/providers/audiobookshelf/__init__.py
Labels: enhancement

#2087 Revamped Crossfade support
  music_assistant/constants.py
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/ffmpeg.py
  music_assistant/helpers/process.py
  music_assistant/models/player_provider.py
  music_assistant/providers/_template_player_provider/__init__.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/bluesound/__init__.py
  music_assistant/providers/builtin_player/__init__.py
  music_assistant/providers/chromecast/__init__.py
  music_assistant/providers/dlna/__init__.py
  music_assistant/providers/fully_kiosk/__init__.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/sonos/const.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/sonos_s1/__init__.py
  music_assistant/providers/squeezelite/__init__.py
Labels: enhancement, bugfix, maintenance

#2088 frontend-2.14.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2086 fix: Recommendations for ABS and iTunes Podcasts
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/itunes_podcasts/__init__.py
  music_assistant/providers/itunes_podcasts/schema.py
  pyproject.toml
Labels: bugfix

#2089 Fix: enqueue next item
  music_assistant/controllers/player_queues.py
Labels: bugfix
