Repository music-assistant/server, pull requests merged in 2025-06, with the labels that each got.

#2206 Fix bug when using random order
  music_assistant/controllers/media/base.py
Labels: maintenance

#2219 Fix typo preventing translation
  music_assistant/controllers/music.py
Labels: maintenance

#2226 Feat: Subsonic: Add configurable recommendations
  music_assistant/providers/opensubsonic/__init__.py
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: enhancement

#2242 Subsonic: Display the newest podcast episodes as front page recommendation
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/fixtures/episodes/no-cover.episode.json
  tests/providers/opensubsonic/fixtures/episodes/no-cover.podcast.json
Labels: enhancement

#2243 Fix Airplay not ungrouping properly
  music_assistant/providers/airplay/provider.py
Labels: bugfix

#2231 tidal: modify pagination function
  music_assistant/providers/tidal/__init__.py
Labels: bugfix

#2248 Introduce (stability/development) stage on providers
  music_assistant/models/provider.py
  music_assistant/providers/airplay/manifest.json
  music_assistant/providers/apple_music/manifest.json
  music_assistant/providers/audible/manifest.json
  music_assistant/providers/audiobookshelf/manifest.json
  music_assistant/providers/bluesound/manifest.json
  music_assistant/providers/builtin/manifest.json
  music_assistant/providers/builtin_player/manifest.json
  music_assistant/providers/chromecast/manifest.json
  music_assistant/providers/deezer/manifest.json
  music_assistant/providers/dlna/manifest.json
  music_assistant/providers/fanarttv/manifest.json
  music_assistant/providers/filesystem_local/manifest.json
  music_assistant/providers/filesystem_smb/manifest.json
  music_assistant/providers/fully_kiosk/manifest.json
  music_assistant/providers/gpodder/manifest.json
  music_assistant/providers/hass/manifest.json
  music_assistant/providers/hass_players/manifest.json
  music_assistant/providers/ibroadcast/manifest.json
  music_assistant/providers/itunes_podcasts/manifest.json
  music_assistant/providers/jellyfin/manifest.json
  music_assistant/providers/lastfm_scrobble/manifest.json
  music_assistant/providers/listenbrainz_scrobble/manifest.json
  music_assistant/providers/lrclib/manifest.json
  music_assistant/providers/musicbrainz/manifest.json
  music_assistant/providers/musiccast/manifest.json
  music_assistant/providers/nugs/manifest.json
  music_assistant/providers/opensubsonic/manifest.json
  music_assistant/providers/player_group/manifest.json
  music_assistant/providers/plex/manifest.json
  music_assistant/providers/podcastfeed/manifest.json
  music_assistant/providers/qobuz/manifest.json
  music_assistant/providers/radiobrowser/manifest.json
  music_assistant/providers/siriusxm/manifest.json
  music_assistant/providers/snapcast/manifest.json
  music_assistant/providers/sonos/manifest.json
  music_assistant/providers/sonos_s1/manifest.json
  music_assistant/providers/soundcloud/manifest.json
  music_assistant/providers/spotify/manifest.json
  music_assistant/providers/spotify_connect/manifest.json
  music_assistant/providers/squeezelite/manifest.json
  music_assistant/providers/subsonic_scrobble/manifest.json
  music_assistant/providers/test/manifest.json
  music_assistant/providers/theaudiodb/manifest.json
  music_assistant/providers/tidal/manifest.json
  music_assistant/providers/tunein/manifest.json
  music_assistant/providers/ytmusic/manifest.json
  pyproject.toml
  requirements_all.txt
Labels: dependencies
