Repository music-assistant/server, pull requests merged in 2025-05, with the labels that each got.

#2162 Adjust file location and Add MusicCast icons
  music_assistant/constants.py
  music_assistant/providers/musiccast/icon.svg
  music_assistant/providers/musiccast/icon_monochrome.svg
Labels: maintenance

#2154 [Airplay] Handle mDNS remove messages without service info
  music_assistant/providers/airplay/provider.py
Labels: enhancement, bugfix

#2167 Subsonic: Fix: Only lookup album for track when an id exists
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: maintenance

#2165 fix: musiccast - volume level handling + device discovery + current track
  music_assistant/providers/musiccast/__init__.py
Labels: bugfix

#2160 Subsonic: Move to new api library
  music_assistant/providers/opensubsonic/manifest.json
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  requirements_all.txt
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/fixtures/episodes/gonic-sample.episode.json
  tests/providers/opensubsonic/fixtures/episodes/gonic-sample.podcast.json
  tests/providers/opensubsonic/fixtures/playlists/gonic-sample.playlist.json
  tests/providers/opensubsonic/fixtures/podcasts/gonic-sample.podcast.json
  tests/providers/opensubsonic/test_parsers.py
Labels: enhancement, maintenance

#2166 Add local lrc lyrics parsing to filesystem provider
  music_assistant/providers/filesystem_local/__init__.py
Labels: enhancement

#2170 Use webserver for auth helper
  music_assistant/controllers/webserver.py
  music_assistant/helpers/auth.py
  music_assistant/providers/apple_music/__init__.py
Labels: enhancement, bugfix

#2161 Update python-snapcast to 2.3.7 (Fix player deletion)
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/snapcast/manifest.json
  requirements_all.txt
Labels: enhancement, bugfix

#2171 Grammar and additional text suggestion
  music_assistant/providers/musiccast/__init__.py
Labels: maintenance

#2178 chore: MusicCast player config improvements + friendly names
  music_assistant/providers/musiccast/__init__.py
  music_assistant/providers/musiccast/constants.py
Labels: maintenance

#2180 Subsonic: Protect all list iteration from possible NoneType
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#2188 Feature: Subsonic: Add bookmark tracking for podcast episodes
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: enhancement

#2168 Add subsonic scrobbler plugin
  music_assistant/providers/subsonic_scrobble/__init__.py
  music_assistant/providers/subsonic_scrobble/icon.svg
  music_assistant/providers/subsonic_scrobble/icon_monochrome.svg
  music_assistant/providers/subsonic_scrobble/manifest.json
Labels: new-provider

#2182 Fix: Prevent NoneType error whenever the track or album name is empty in a Plex playlist
  music_assistant/providers/plex/__init__.py
Labels: bugfix

#2097 Chore: Add mypy for helpers
  music_assistant/helpers/api.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/auth.py
  music_assistant/helpers/compare.py
  music_assistant/helpers/database.py
  music_assistant/helpers/dsp.py
  music_assistant/helpers/ffmpeg.py
  music_assistant/helpers/images.py
  music_assistant/helpers/playlists.py
  music_assistant/helpers/process.py
  music_assistant/helpers/tags.py
  music_assistant/helpers/throttle_retry.py
  music_assistant/helpers/upnp.py
  music_assistant/helpers/util.py
  music_assistant/helpers/webserver.py
  pyproject.toml
Labels: maintenance

#2181 chore/fix: Subsonic: Update parsers and tests
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/fixtures/tracks/spec-child.album.json
  tests/providers/opensubsonic/fixtures/tracks/spec-child.track.json
  tests/providers/opensubsonic/test_parsers.py
Labels: bugfix, maintenance

#2191 fix: unbound library_items
  music_assistant/models/music_provider.py
Labels: bugfix

#2189 Improve sync stability by adapting to diff trend shifts
  music_assistant/providers/squeezelite/__init__.py
Labels: enhancement

#2183 safer get for optional chromecast param "queue_item_id"
  music_assistant/providers/chromecast/__init__.py
Labels: bugfix

#2193 frontend-2.15.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2194 Chore: Separate BrowseFolder from MediaItemType
  music_assistant/controllers/music.py
  music_assistant/controllers/player_queues.py
  music_assistant/helpers/compare.py
  music_assistant/models/music_provider.py
  music_assistant/providers/_template_music_provider/__init__.py
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/radiobrowser/__init__.py
  music_assistant/providers/siriusxm/__init__.py
  music_assistant/providers/tidal/__init__.py
Labels: maintenance

#2202 Bump YT Music dependencies.
  music_assistant/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix, dependencies

#2203 Fix: Subsonic Scrobble: Split the internal id for Podcast Episode
  music_assistant/providers/subsonic_scrobble/__init__.py
Labels: maintenance

#2204 Search radio stations on tunein provider
  music_assistant/providers/tunein/__init__.py
Labels: enhancement
