Repository music-assistant/server, pull requests merged in 2025-07, with the labels that each got.

#2264 YTMusic: Fix extractor error
  music_assistant/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: bugfix, backport-to-stable

#2256 fix: non-ascii characters in didl_lite metadata
  music_assistant/helpers/upnp.py
Labels: bugfix, backport-to-stable

#2251 Fix Alexa player provider bugs during experimental testing
  music_assistant/helpers/webserver.py
  music_assistant/providers/alexa/__init__.py
Labels: maintenance

#2268 Add backport pipeline
  .github/workflows/backport-to-stable.yml
Labels: ci

#2275 Added recommendations to the SoundCloud provider
  music_assistant/providers/soundcloud/__init__.py
  music_assistant/providers/soundcloud/manifest.json
  requirements_all.txt
Labels: enhancement
