Repository music-assistant/server, pull requests merged in 2025-04, with the labels that each got.

#2090 Fix radio stream playback
  music_assistant/controllers/streams.py
Labels: bugfix

#2092 YT Music: Fix missing track thumbs
  music_assistant/providers/ytmusic/helpers.py
Labels: bugfix

#2093 fix: abs - recommendation, series handling
  music_assistant/providers/audiobookshelf/__init__.py
Labels: bugfix

#2094 frontend-2.14.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2095 fix: Remove unused Sample Rate config from the Web Player
  music_assistant/providers/builtin_player/__init__.py
Labels: bugfix

#2096 frontend-2.14.8
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2099 Snapcast re add on player config removed
  music_assistant/providers/snapcast/__init__.py
Labels: enhancement, bugfix

#2105 Several small fixes for playback and enqueuing
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/providers/audible/audible_helper.py
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/ytmusic/__init__.py
Labels: bugfix

#2103 Snapcast fix external server stream
  music_assistant/providers/snapcast/__init__.py
Labels: bugfix

#2107 Fix usage of album loudness during playback
  music_assistant/controllers/streams.py
Labels: bugfix

#2108 Also use previous track to work out if an album is playing
  music_assistant/controllers/player_queues.py
Labels: enhancement

#2106 Audible: inverse of the suppoorted content type rule
  music_assistant/providers/audible/audible_helper.py
Labels: bugfix

#2119 frontend-2.14.9
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2115 Enhancement: gPodder - optional handling of delete action
  music_assistant/providers/gpodder/__init__.py
  music_assistant/providers/gpodder/client.py
Labels: enhancement

#2120 Various minor bugfixes and enhancements
  music_assistant/controllers/music.py
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/players.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/providers/airplay/raop.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/podcastfeed/__init__.py
Labels: bugfix

#2118 Tidal: Various playlist and mix changes
  music_assistant/providers/tidal/__init__.py
Labels: maintenance

#2121 Fix cast players not available at startup
  music_assistant/controllers/players.py
  music_assistant/providers/chromecast/helpers.py
Labels: bugfix

#2100 Make Zeroconf only bind to the default interface
  music_assistant/mass.py
Labels: enhancement

#2122 Round loudness measurements to two digits
  music_assistant/controllers/music.py
Labels: maintenance

#2125 add open home badge
  README.md
Labels: maintenance

#2124 fix: library items removed by music provider not removed in MA library
  music_assistant/models/music_provider.py
Labels: bugfix

#2127 Fix AirPlay branding
  DEVELOPMENT.md
  music_assistant/providers/_template_music_provider/__init__.py
  music_assistant/providers/_template_player_provider/__init__.py
  music_assistant/providers/_template_plugin_provider/__init__.py
  music_assistant/providers/airplay/__init__.py
  music_assistant/providers/airplay/helpers.py
  music_assistant/providers/airplay/manifest.json
  music_assistant/providers/airplay/player.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/airplay/raop.py
  music_assistant/providers/filesystem_smb/__init__.py
  music_assistant/providers/sonos/const.py
  music_assistant/providers/sonos/provider.py
  pyproject.toml
Labels: maintenance

#2128 YTMusic: Add recommendations
  music_assistant/providers/ytmusic/__init__.py
  music_assistant/providers/ytmusic/constants.py
  music_assistant/providers/ytmusic/helpers.py
Labels: enhancement

#2126 Fix all lowercase display names for AirPlay players
  music_assistant/providers/airplay/provider.py
Labels: bugfix

#2081 Add lrc lyric parsing to tidal
  music_assistant/providers/tidal/__init__.py
Labels: enhancement

#2104 Audible: fixes type error of release_date metadata
  music_assistant/providers/audible/audible_helper.py
Labels: bugfix

#2123 Add LRCLIB lyrics metadata provider
  music_assistant/providers/lrclib/__init__.py
  music_assistant/providers/lrclib/icon.svg
  music_assistant/providers/lrclib/manifest.json
Labels: new-provider

#2134 Suggested grammar change
  music_assistant/constants.py
Labels: maintenance

#2135 Tidal: Add limits to certain api calls
  music_assistant/providers/tidal/__init__.py
Labels: bugfix

#2136 Tidal: Modify recommendations setup
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/tidal_page_parser.py
Labels: enhancement

#2143 Audible: adding multipart audiobooks
  music_assistant/providers/audible/audible_helper.py
Labels: bugfix

#2144 tidal: allow audio quality switching after authentication
  music_assistant/providers/tidal/__init__.py
Labels: enhancement

#1974 Add nugs.net music provider
  music_assistant/providers/nugs/__init__.py
  music_assistant/providers/nugs/icon.svg
  music_assistant/providers/nugs/manifest.json
Labels: new-provider

#2148 frontend-2.15.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2145 Several improvements to announcements
  music_assistant/controllers/streams.py
  music_assistant/providers/snapcast/__init__.py
Labels: enhancement

#2151 Volume fixes for native announcements
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/sonos/provider.py
Labels: enhancement, bugfix

#2149 Add debug message about concatenating announcement stream
  music_assistant/controllers/streams.py
Labels: enhancement

#2142 Add Yamaha MusicCast provider
  music_assistant/constants.py
  music_assistant/helpers/upnp.py
  music_assistant/providers/dlna/__init__.py
  music_assistant/providers/musiccast/__init__.py
  music_assistant/providers/musiccast/avt_helpers.py
  music_assistant/providers/musiccast/constants.py
  music_assistant/providers/musiccast/icon.svg
  music_assistant/providers/musiccast/manifest.json
  music_assistant/providers/musiccast/musiccast.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/sonos_s1/__init__.py
  requirements_all.txt
Labels: new-provider

#2150 feat/musickit-auth Support for Apple Music authentication in web UI
  music_assistant/providers/apple_music/__init__.py
  music_assistant/providers/apple_music/musickit_auth/musickit_wrapper.css
  music_assistant/providers/apple_music/musickit_auth/musickit_wrapper.html
Labels: enhancement, new-feature
