Repository music-assistant/server, pull requests merged in 2025-08, with the labels that each got.

#2270 Fix library query with random order and improve maintainability
  music_assistant/controllers/media/albums.py
  music_assistant/controllers/media/base.py
Labels: bugfix, backport-to-stable

#2287 Add URL example
  music_assistant/providers/audiobookshelf/__init__.py
Labels: enhancement, backport-to-stable

#2305 Fix broken state updates for SnapCast
  music_assistant/providers/snapcast/provider.py
Labels: bugfix

#2271 Attempt to fix "This Device" disappearing and reappearing on Firefox
  music_assistant/providers/builtin_player/player.py
Labels: bugfix, backport-to-stable

#2308 Add helpers to setup aiohttp session
  music_assistant/constants.py
  music_assistant/helpers/aiohttp_client.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/images.py
  music_assistant/helpers/ssl.py
  music_assistant/mass.py
  music_assistant/providers/fanarttv/__init__.py
  music_assistant/providers/fully_kiosk/provider.py
  music_assistant/providers/hass/__init__.py
  music_assistant/providers/jellyfin/__init__.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/sonos/provider.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement

#2312 Bump models to 1.1.53
  pyproject.toml
  requirements_all.txt
  tests/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
Labels: dependencies

#2274 Add CLAUDE.md development guide
  CLAUDE.md
Labels: enhancement

#2316 Fallback to standard pip for package installs
  music_assistant/helpers/util.py
Labels: bugfix, backport-to-stable

#2318 Fix issues with dynamically installing packages into the running server
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.base
  music_assistant/helpers/util.py
  music_assistant/providers/ytmusic/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: bugfix, backport-to-stable

#2319 Fix playback with the Web Player for iOS devices
  music_assistant/providers/builtin_player/player.py
Labels: bugfix

#2333 frontend-2.15.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2334 Disable new PO token generation to avoid warnings in the logs.
  music_assistant/providers/ytmusic/__init__.py
Labels: bugfix, backport-to-stable

#2329 Spotify refactor
  music_assistant/controllers/metadata.py
  music_assistant/models/music_provider.py
  music_assistant/providers/spotify/__init__.py
  music_assistant/providers/spotify/constants.py
  music_assistant/providers/spotify/helpers.py
  music_assistant/providers/spotify/parsers.py
  music_assistant/providers/spotify/provider.py
  music_assistant/providers/spotify/streaming.py
Labels: maintenance

#2335 Some follow-up fixes (esp. for groups) after the Player refactor
  music_assistant/controllers/config.py
  music_assistant/controllers/players.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/musiccast/provider.py
  music_assistant/providers/snapcast/provider.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/sonos_s1/provider.py
  music_assistant/providers/squeezelite/provider.py
Labels: enhancement, bugfix

#2336 Fix stop command on some Home Assistant players
  music_assistant/providers/hass_players/player.py
Labels: bugfix, backport-to-stable

#2341 Fix missing file breaks queue
  music_assistant/providers/filesystem_local/__init__.py
Labels: bugfix, backport-to-stable

#2362 Some small follow-up fixes after Players controller refactor
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/players.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/squeezelite/player.py
  music_assistant/providers/squeezelite/provider.py
Labels: bugfix
