Repository music-assistant/server, pull requests merged in 2025-02, with the labels that each got.

#1929 fix: correctly refresh streamdetails in group/ungroup scenarios
  music_assistant/controllers/player_queues.py
Labels: bugfix

#1930 chore: Clarify exception reason for similar tracks in Tidal provider
  music_assistant/providers/tidal/helpers.py
Labels: maintenance

#1928 fix: show chapters in ABS audiobook view
  music_assistant/providers/audiobookshelf/__init__.py
Labels: bugfix

#1931 frontend-2.10.11
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1937 Add audiobooks and podcasts support to local filesystem provider
  music_assistant/controllers/media/podcasts.py
  music_assistant/helpers/ffmpeg.py
  music_assistant/helpers/process.py
  music_assistant/helpers/tags.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/filesystem_local/constants.py
  music_assistant/providers/filesystem_local/helpers.py
  music_assistant/providers/filesystem_smb/__init__.py
Labels: new-feature

#1940 fix: remove `is_leader` for better grouping in the Audio Pipeline
  music_assistant/helpers/audio.py
Labels: bugfix

#1942 frontend-2.11.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1944 Fix Podcast and Audiobook support on SMB Filesystem provider
  music_assistant/controllers/music.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/filesystem_smb/__init__.py
Labels: bugfix

#1946 Fix reporting of playback progress
  music_assistant/controllers/player_queues.py
  music_assistant/helpers/util.py
Labels: enhancement, bugfix

#1950 frontend-2.11.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1949 Feat: Use the player prefered (lossless) format in universal groups
  music_assistant/controllers/streams.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/player_group/ugp_stream.py
Labels: enhancement

#1957 frontend-2.11.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1952 Fix: Resolve playlist won't go up two relative levels.
  music_assistant/providers/filesystem_local/__init__.py
Labels: enhancement, bugfix

#1958 Fix: Correct codeowner username in Snapcast manifest
  music_assistant/providers/snapcast/manifest.json
Labels: maintenance

#1960 frontend-2.11.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1948 ABS: Rewrite of provider, couple new features
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/abs_client.py
  music_assistant/providers/audiobookshelf/abs_schema.py
  music_assistant/providers/audiobookshelf/manifest.json
  music_assistant/providers/audiobookshelf/parsers.py
  requirements_all.txt
  tests/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
Labels: enhancement, refactor

#1959 Fix: Double grouped players with Universal Groups
  music_assistant/providers/player_group/__init__.py
Labels: bugfix

#1961 Chore: bump aioaudiobookshelf library to version 0.1.1
  music_assistant/providers/audiobookshelf/manifest.json
  requirements_all.txt
Labels: bugfix, dependencies

#1962 frontend-2.11.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1965 frontend-2.11.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1966 Fix: Subsonic: Use any parent link when enumerating songs
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: bugfix

#1968 fix(tidal): fix track playback with lyrics error suppression
  music_assistant/providers/tidal/helpers.py
Labels: bugfix

#1969 Adding `number` as valid volume player control entities
  music_assistant/helpers/util.py
  music_assistant/providers/hass/__init__.py
Labels: enhancement

#1970 A bit of cleanup in ABS Provider
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/constants.py
  music_assistant/providers/audiobookshelf/helpers.py
Labels: enhancement, maintenance

#1972 frontend-2.11.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1976 fix: only MediaItemType has provider_mappings
  music_assistant/controllers/music.py
Labels: maintenance

#1975 frontend-2.11.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1978 frontend-2.11.8
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1971 Enhancement: Implement resume state syncing for ABS provider
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/helpers.py
  music_assistant/providers/audiobookshelf/manifest.json
  music_assistant/providers/audiobookshelf/parsers.py
  requirements_all.txt
Labels: enhancement

#1979 frontend-2.11.10
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1980 Fix assertion error when trying to save a provider config
  music_assistant/helpers/api.py
Labels: bugfix

#1984 fix(tidal): refresh access token correctly
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/helpers.py
Labels: bugfix

#1987 frontend-2.11.11
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1989 Add caching of audio data to fix streams not starting fast enough
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/ffmpeg.py
  music_assistant/helpers/util.py
  music_assistant/providers/apple_music/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement, bugfix

#1991 Fix Large PodcastEpisode listings not working
  music_assistant/controllers/media/podcasts.py
  music_assistant/controllers/player_queues.py
  music_assistant/models/music_provider.py
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  music_assistant/providers/podcastfeed/__init__.py
  music_assistant/providers/test/__init__.py
  music_assistant/providers/ytmusic/__init__.py
Labels: enhancement, bugfix

#1993 frontend-2.12.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1992 Various (very) small bugfixes and enhancements
  music_assistant/constants.py
  music_assistant/controllers/config.py
  music_assistant/controllers/players.py
  music_assistant/controllers/streams.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/hass_players/__init__.py
Labels: enhancement, bugfix

#1990 ABS: Login via API key
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/constants.py
  music_assistant/providers/audiobookshelf/manifest.json
  requirements_all.txt
Labels: enhancement
