Repository music-assistant/server, pull requests merged in 2025-09, with the labels that each got.

#2372 Fix snapcast grouping after the player model refactor
  music_assistant/providers/snapcast/player.py
  music_assistant/providers/snapcast/provider.py
Labels: bugfix

#2364 Fix group volume and player state after Players controller refactor
  music_assistant/controllers/players.py
  music_assistant/models/player.py
Labels: bugfix

#2383 Fix saving of player settings on powered off players
  music_assistant/controllers/players.py
Labels: bugfix

#2360 Switch to static logo images in Radio Paradise provider
  music_assistant/providers/radioparadise/__init__.py
Labels: enhancement

#2359 Bluesound native grouping and control of external sources
  music_assistant/providers/bluesound/const.py
  music_assistant/providers/bluesound/manifest.json
  music_assistant/providers/bluesound/player.py
  music_assistant/providers/bluesound/provider.py
  requirements_all.txt
Labels: enhancement

#2387 Don't remove players on load in Home Assistant Player Provider
  music_assistant/providers/hass_players/provider.py
Labels: bugfix

#2388 Fix issues when disabling a player provider
  music_assistant/controllers/config.py
  music_assistant/controllers/players.py
Labels: bugfix

#2380 Update builtin player provider icons
  music_assistant/providers/builtin_player/icon.svg
  music_assistant/providers/builtin_player/icon_monochrome.svg
Labels: maintenance

#2392 Add caching and fix audiobook podcast mixup
  music_assistant/providers/spotify/provider.py
Labels: enhancement, bugfix

#2379 Audiobookshelf: Implement new JWT authorization
  music_assistant/helpers/audio.py
  music_assistant/helpers/ffmpeg.py
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/constants.py
  music_assistant/providers/audiobookshelf/manifest.json
  requirements_all.txt
Labels: maintenance

#2394 refactor: Split Radio Paradise provider
  music_assistant/providers/radioparadise/__init__.py
  music_assistant/providers/radioparadise/constants.py
  music_assistant/providers/radioparadise/helpers.py
  music_assistant/providers/radioparadise/parsers.py
  music_assistant/providers/radioparadise/provider.py
Labels: maintenance

#2395 Spotify Podcast Final caching and fix image quality
  music_assistant/providers/spotify/parsers.py
  music_assistant/providers/spotify/provider.py
Labels: enhancement

#2403 Allow chime URL to be customized for Announcements
  music_assistant/constants.py
  music_assistant/controllers/players.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/util.py
  music_assistant/models/player.py
  music_assistant/providers/airplay/player.py
  music_assistant/providers/snapcast/player.py
  music_assistant/providers/squeezelite/player.py
  music_assistant/providers/universal_group/player.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement

#2373 Expose `grouping` field on tracks
  music_assistant/providers/filesystem_local/__init__.py
Labels: enhancement

#2408 Spotify. Add played status sync on podcast episode load
  music_assistant/providers/spotify/provider.py
Labels: enhancement

#2406 Add live and soundtrack album types
  music_assistant/constants.py
  music_assistant/helpers/tags.py
  music_assistant/helpers/util.py
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/spotify/parsers.py
Labels: new-feature

#2413 Several small (typing) fixes for the Deezer provider
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/deezer/gw_client.py
Labels: bugfix, maintenance

#2332 Add (Roku) Media Assistant provider
  music_assistant/providers/roku_media_assistant/__init__.py
  music_assistant/providers/roku_media_assistant/constants.py
  music_assistant/providers/roku_media_assistant/icon.svg
  music_assistant/providers/roku_media_assistant/icon_monochrome.svg
  music_assistant/providers/roku_media_assistant/manifest.json
  music_assistant/providers/roku_media_assistant/player.py
  music_assistant/providers/roku_media_assistant/provider.py
  requirements_all.txt
Labels: new-provider

#2425 gpodder/ itunes/ rssfeed: fix bad header for certain podcasts
  music_assistant/helpers/podcast_parsers.py
  music_assistant/providers/gpodder/__init__.py
  music_assistant/providers/itunes_podcasts/__init__.py
  music_assistant/providers/podcastfeed/__init__.py
Labels: bugfix, backport-to-stable

#2348 Add Resonate Provider
  music_assistant/providers/resonate/__init__.py
  music_assistant/providers/resonate/icon.svg
  music_assistant/providers/resonate/icon_monochrome.svg
  music_assistant/providers/resonate/manifest.json
  music_assistant/providers/resonate/player.py
  music_assistant/providers/resonate/provider.py
  requirements_all.txt
Labels: new-provider

#2429 More grouping fixes after the player refactor
  music_assistant/controllers/players.py
  music_assistant/models/player.py
  music_assistant/providers/_demo_player_provider/player.py
  music_assistant/providers/squeezelite/player.py
  music_assistant/providers/universal_group/player.py
  pyproject.toml
  requirements_all.txt
Labels: bugfix

#2431 Add or update stage key in manifest.json
  music_assistant/providers/apple_music/manifest.json
  music_assistant/providers/ard_audiothek/manifest.json
  music_assistant/providers/bluesound/manifest.json
  music_assistant/providers/genius_lyrics/manifest.json
  music_assistant/providers/lastfm_scrobble/manifest.json
  music_assistant/providers/listenbrainz_scrobble/manifest.json
  music_assistant/providers/lrclib/manifest.json
  music_assistant/providers/musiccast/manifest.json
  music_assistant/providers/nugs/manifest.json
  music_assistant/providers/podcast-index/manifest.json
  music_assistant/providers/radioparadise/manifest.json
  music_assistant/providers/roku_media_assistant/manifest.json
  music_assistant/providers/universal_group/manifest.json
  music_assistant/providers/ytmusic/manifest.json
Labels: maintenance

#2411 Add Internet Archive Provider
  music_assistant/providers/internet_archive/__init__.py
  music_assistant/providers/internet_archive/constants.py
  music_assistant/providers/internet_archive/helpers.py
  music_assistant/providers/internet_archive/icon.svg
  music_assistant/providers/internet_archive/icon_monochrome.svg
  music_assistant/providers/internet_archive/manifest.json
  music_assistant/providers/internet_archive/parsers.py
  music_assistant/providers/internet_archive/provider.py
  music_assistant/providers/internet_archive/streaming.py
Labels: new-provider

#2433 Several improvements to the Smartfades feature
  music_assistant/controllers/music.py
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/smart_fades.py
  music_assistant/models/smart_fades.py
  music_assistant/providers/sonos/player.py
Labels: enhancement, bugfix

#2439 mypy fixes for webserver helper
  music_assistant/helpers/webserver.py
  pyproject.toml
Labels: maintenance

#2436 mypy fixes for Spotify provider
  music_assistant/providers/spotify/provider.py
  pyproject.toml
Labels: maintenance

#2449 mypy fixes for TuneIn
  music_assistant/providers/tunein/__init__.py
  pyproject.toml
Labels: maintenance

#2455 Fix 403 error on podcast playback
  music_assistant/providers/podcastfeed/__init__.py
Labels: bugfix, backport-to-stable
