Repository music-assistant/server, pull requests merged in 2025-10, with the labels that each got.

#2444 Various Playergroup fixes
  music_assistant/controllers/music.py
  music_assistant/controllers/players/__init__.py
  music_assistant/controllers/players/player_controller.py
  music_assistant/controllers/players/sync_groups.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/mass.py
  music_assistant/models/player.py
  music_assistant/models/player_provider.py
  music_assistant/providers/_demo_player_provider/__init__.py
  music_assistant/providers/airplay/__init__.py
  music_assistant/providers/bluesound/__init__.py
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/musiccast/__init__.py
  music_assistant/providers/podcast_index/__init__.py
  music_assistant/providers/podcast_index/constants.py
  music_assistant/providers/podcast_index/helpers.py
  music_assistant/providers/podcast_index/icon.svg
  music_assistant/providers/podcast_index/icon_monochrome.svg
  music_assistant/providers/podcast_index/manifest.json
  music_assistant/providers/podcast_index/provider.py
  music_assistant/providers/resonate/provider.py
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/sonos/__init__.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/sonos_s1/__init__.py
  music_assistant/providers/squeezelite/__init__.py
  music_assistant/providers/universal_group/player.py
  pyproject.toml
Labels: bugfix, maintenance

#2467 frontend-2.16.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2468 Fix current track not updating correctly
  music_assistant/models/player.py
Labels: bugfix

#2469 Fix playergroup migration
  music_assistant/controllers/config.py
  music_assistant/controllers/players/sync_groups.py
  music_assistant/models/player.py
Labels: bugfix

#2471 frontend-2.16.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2475 Various small bugfixes reported in the beta
  music_assistant/controllers/players/player_controller.py
  music_assistant/controllers/players/sync_groups.py
  music_assistant/controllers/streams.py
  music_assistant/providers/squeezelite/player.py
  music_assistant/providers/ytmusic/__init__.py
Labels: bugfix

#2472 Various improvements to the DI Provider
  music_assistant/providers/digitally_incorporated/__init__.py
Labels: enhancement, bugfix

#2450 mypy fixes for SiriusXM
  music_assistant/providers/siriusxm/__init__.py
Labels: maintenance

#2476 frontend-2.16.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#2477 Fix: Smart fades beat alignment
  music_assistant/helpers/smart_fades.py
Labels: bugfix

#2479 Fix cache data not persisting cross restarts/updates
  Dockerfile
  music_assistant/__main__.py
Labels: bugfix

#2492 Add Recommendations to nugs.net
  music_assistant/providers/nugs/__init__.py
Labels: enhancement
