Repository music-assistant/server, pull requests merged in 2025-01, with the labels that each got.

#1823 Fix support links
  README.md
Labels: maintenance

#1824 Fix: Disable the DSP by default
  music_assistant/controllers/config.py
Labels: bugfix

#1826 frontend-2.10.0
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1827 frontend-2.10.1
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1829 A bunch of fixes for the enqueue and radio mode logic
  music_assistant/controllers/media/albums.py
  music_assistant/controllers/media/artists.py
  music_assistant/controllers/media/audiobooks.py
  music_assistant/controllers/media/base.py
  music_assistant/controllers/media/playlists.py
  music_assistant/controllers/media/podcasts.py
  music_assistant/controllers/media/radio.py
  music_assistant/controllers/media/tracks.py
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/models/music_provider.py
  music_assistant/models/plugin.py
  music_assistant/providers/_template_music_provider/__init__.py
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/dlna/__init__.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  music_assistant/providers/plex/__init__.py
  music_assistant/providers/qobuz/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: enhancement, bugfix

#1830 Remove the devcontainer because its unmaintained
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  DEVELOPMENT.md
Labels: maintenance

#1817 Add RSS Feed Podcast provider
  music_assistant/providers/podcastfeed/__init__.py
  music_assistant/providers/podcastfeed/icon.svg
  music_assistant/providers/podcastfeed/manifest.json
  pyproject.toml
  requirements_all.txt
Labels: new-provider

#1831 frontend-2.10.2
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1837 frontend-2.10.3
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1832 Fix error on missing key in RSS Podcast data.
  DEVELOPMENT.md
  music_assistant/providers/podcastfeed/__init__.py
Labels: bugfix

#1838 frontend-2.10.4
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1843 Fix: Avoid extra call to get playlist metadata when fetching playlist tracks in Jellyfin
  music_assistant/providers/jellyfin/__init__.py
Labels: bugfix

#1844 Performance improvements for filesystem provider
  music_assistant/controllers/players.py
  music_assistant/helpers/tags.py
  music_assistant/providers/builtin/__init__.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/filesystem_local/helpers.py
  music_assistant/providers/hass_players/__init__.py
  music_assistant/providers/plex/__init__.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/tidal/__init__.py
  tests/core/test_tags.py
Labels: enhancement

#1847 fix: Make sure that Jellyfin playlists are sorted and paginated
  music_assistant/providers/jellyfin/__init__.py
  music_assistant/providers/jellyfin/manifest.json
  requirements_all.txt
Labels: bugfix, python

#1846 Small fix for checking playlist url
  music_assistant/helpers/playlists.py
Labels: bugfix

#1848 chore: mypy for airplay
  music_assistant/providers/airplay/__init__.py
  music_assistant/providers/airplay/helpers.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/airplay/raop.py
  pyproject.toml
Labels: maintenance

#1851 Mypy fixes
  music_assistant/constants.py
  music_assistant/controllers/media/albums.py
  music_assistant/controllers/media/artists.py
  music_assistant/controllers/media/audiobooks.py
  music_assistant/controllers/media/base.py
  music_assistant/controllers/media/playlists.py
  music_assistant/controllers/media/podcasts.py
  music_assistant/controllers/media/radio.py
  music_assistant/controllers/media/tracks.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/airplay/raop.py
  music_assistant/providers/filesystem_local/__init__.py
  music_assistant/providers/plex/__init__.py
  music_assistant/providers/radiobrowser/__init__.py
  music_assistant/providers/test/__init__.py
  pyproject.toml
  requirements_all.txt
  tests/core/test_helpers.py
Labels: ci, maintenance

#1839 Feat: Add multi device DSP support
  music_assistant/controllers/players.py
  music_assistant/helpers/audio.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/player_group/ugp_stream.py
  music_assistant/providers/slimproto/__init__.py
  music_assistant/providers/snapcast/__init__.py
Labels: enhancement, new-feature

#1854 chore: mypy for sonos s1
  music_assistant/mass.py
  music_assistant/providers/sonos_s1/__init__.py
  music_assistant/providers/sonos_s1/helpers.py
  music_assistant/providers/sonos_s1/player.py
  pyproject.toml
Labels: maintenance

#1842 Audible audiobook provider
  music_assistant/providers/audible/__init__.py
  music_assistant/providers/audible/audible_helper.py
  music_assistant/providers/audible/icon.svg
  music_assistant/providers/audible/manifest.json
  requirements_all.txt
Labels: new-provider

#1852 Varuous fixes and enhancements for the Soundcloud provider
  music_assistant/providers/soundcloud/__init__.py
  music_assistant/providers/soundcloud/manifest.json
  requirements_all.txt
Labels: enhancement, bugfix

#1860 fix: typo
  music_assistant/providers/musicbrainz/__init__.py
Labels: bugfix

#1859 Opensubsonic tests for artist 'parsing'
  .pre-commit-config.yaml
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  tests/providers/opensubsonic/__init__.py
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/fixtures/artists/spec-artistid3.artist.json
  tests/providers/opensubsonic/fixtures/artists/spec-artistid3.info.json
  tests/providers/opensubsonic/fixtures/artists/spec-sample.artist.json
  tests/providers/opensubsonic/fixtures/artists/spec-sample.info.json
  tests/providers/opensubsonic/test_parsers.py
Labels: ci

#1865 chore: add album parsing tests for opensubsonic
  music_assistant/providers/opensubsonic/parsers.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  tests/providers/opensubsonic/__snapshots__/test_parsers.ambr
  tests/providers/opensubsonic/fixtures/albums/spec.album.json
  tests/providers/opensubsonic/fixtures/albums/spec.info.json
  tests/providers/opensubsonic/test_parsers.py
Labels: ci

#1863 chore: mypy for mass.py
  music_assistant/mass.py
  pyproject.toml
Labels: maintenance

#1862 chore: mypy for fanart.tv
  music_assistant/providers/fanarttv/__init__.py
  pyproject.toml
  requirements_all.txt
Labels: maintenance

#1871 chore: mypy for template music provider
  music_assistant/providers/_template_music_provider/__init__.py
  pyproject.toml
Labels: ci, maintenance

#1872 Fix: Audio streaming hangs suddenly at the end of a track
  Dockerfile
  Dockerfile.base
  music_assistant/helpers/audio.py
  music_assistant/helpers/ffmpeg.py
Labels: bugfix

#1874 frontend-2.10.5
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1873 use the trixie-slim image
  Dockerfile.base
Labels: ci

#1876 chore: mypy for template player provider
  music_assistant/providers/_template_player_provider/__init__.py
  pyproject.toml
Labels: ci, maintenance

#1857 Add Audiobookshelf audiobooks & podcast provider
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/abs_client.py
  music_assistant/providers/audiobookshelf/abs_schema.py
  music_assistant/providers/audiobookshelf/icon.svg
  music_assistant/providers/audiobookshelf/manifest.json
Labels: new-provider

#1875 Feat: Add DSP pipeline details to stream information
  music_assistant/controllers/player_queues.py
  music_assistant/helpers/audio.py
Labels: new-feature

#1879 Fix: DSP edge cases around groups
  music_assistant/controllers/players.py
  music_assistant/helpers/audio.py
Labels: bugfix

#1881 frontend-2.10.6
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1882 Switch to ffmpeg 7.1 + other fixes for audio streaming
  Dockerfile
  Dockerfile.base
  music_assistant/helpers/audio.py
  music_assistant/providers/airplay/bin/cliraop-linux-aarch64
  music_assistant/providers/airplay/bin/cliraop-linux-x86_64
  music_assistant/providers/spotify/__init__.py
Labels: bugfix, maintenance

#1884 frontend-2.10.7
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1885 Allow for advanced networking in the Sonos provider.
  music_assistant/providers/sonos/__init__.py
  music_assistant/providers/sonos/provider.py
Labels: enhancement

#1887 Feat: Ability to use Audiobookshelf Sessions/ HLS Stream
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/abs_client.py
  music_assistant/providers/audiobookshelf/abs_schema.py
Labels: enhancement

#1886 Fix: Check for Chromecast groups in DSP compatiblity check
  music_assistant/helpers/audio.py
Labels: bugfix

#1890 fix: add missing AudioFormat metadata to Jellyfin provider
  music_assistant/providers/jellyfin/__init__.py
  music_assistant/providers/jellyfin/manifest.json
  music_assistant/providers/jellyfin/parsers.py
  requirements_all.txt
  tests/providers/jellyfin/__snapshots__/test_parsers.ambr
  tests/providers/jellyfin/fixtures/tracks/do_i_wanna_know.json
Labels: bugfix, python

#1891 chore: add mypy for hass
  music_assistant/providers/hass/__init__.py
  pyproject.toml
Labels: maintenance

#1893 chore: ruff 0.9.1
  music_assistant/controllers/cache.py
  music_assistant/controllers/config.py
  music_assistant/controllers/media/base.py
  music_assistant/controllers/music.py
  music_assistant/controllers/player_queues.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/database.py
  music_assistant/helpers/webserver.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/filesystem_smb/__init__.py
  music_assistant/providers/hass_players/__init__.py
  music_assistant/providers/opensubsonic/__init__.py
  music_assistant/providers/opensubsonic/sonic_provider.py
  music_assistant/providers/qobuz/__init__.py
  music_assistant/providers/spotify/__init__.py
  music_assistant/providers/tunein/__init__.py
  pyproject.toml
  scripts/profiler.py
Labels: maintenance

#1899 chore: update ci versions to match docker, pyproject.toml, etc
  .github/workflows/test.yml
  DEVELOPMENT.md
  pyproject.toml
Labels: ci

#1892 Fix: Deezer tracks that have been replaced with a newer version fail to play
  music_assistant/providers/deezer/__init__.py
  music_assistant/providers/deezer/gw_client.py
Labels: bugfix

#1900 Fix: Provide a proper track number for Deezer tracks if available
  music_assistant/providers/deezer/__init__.py
Labels: bugfix

#1898 Chore: Audiobookshelf - adapt schema to reflect the naming scheme used in the API docs
  music_assistant/providers/audiobookshelf/__init__.py
  music_assistant/providers/audiobookshelf/abs_client.py
  music_assistant/providers/audiobookshelf/abs_schema.py
Labels: maintenance

#1902 frontend-2.10.8
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1905 Fix: Use Deezer record_type to set the album type of Deezer albums
  music_assistant/providers/deezer/__init__.py
Labels: bugfix

#1904 Remove scrobble from Subsonic provider
  music_assistant/providers/opensubsonic/sonic_provider.py
Labels: maintenance

#1901 fix: small refactor of tidal auth function
  music_assistant/providers/tidal/__init__.py
Labels: bugfix

#1907 frontend-2.10.9
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1913 Switch the Soundcloud artist tracks to the full listing
  music_assistant/providers/soundcloud/__init__.py
Labels: enhancement, bugfix

#1911 Feat: add support for monochrome provider icons
  music_assistant/mass.py
Labels: enhancement

#1922 feat: add missing file extensions for filesystem provider
  music_assistant/providers/filesystem_local/__init__.py
Labels: enhancement

#1920 feat: attach output format to the player
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/streams.py
  music_assistant/helpers/audio.py
  music_assistant/providers/airplay/raop.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/slimproto/__init__.py
  music_assistant/providers/snapcast/__init__.py
Labels: enhancement

#1921 Feat: attach codec used in the input file to the streamdetails
  music_assistant/controllers/player_queues.py
  music_assistant/helpers/audio.py
  music_assistant/helpers/ffmpeg.py
Labels: enhancement

#1923 Feat: Add support for PEQ preamp
  music_assistant/helpers/dsp.py
Labels: new-feature

#1924 YTMusic: Add podcast support
  music_assistant/providers/ytmusic/__init__.py
  music_assistant/providers/ytmusic/helpers.py
  music_assistant/providers/ytmusic/manifest.json
  requirements_all.txt
Labels: enhancement, bugfix

#1925 Add Player Controls feature
  music_assistant/constants.py
  music_assistant/controllers/player_queues.py
  music_assistant/controllers/players.py
  music_assistant/models/player_provider.py
  music_assistant/providers/_template_player_provider/__init__.py
  music_assistant/providers/airplay/provider.py
  music_assistant/providers/bluesound/__init__.py
  music_assistant/providers/chromecast/__init__.py
  music_assistant/providers/dlna/__init__.py
  music_assistant/providers/fully_kiosk/__init__.py
  music_assistant/providers/hass/__init__.py
  music_assistant/providers/hass/constants.py
  music_assistant/providers/hass_players/__init__.py
  music_assistant/providers/player_group/__init__.py
  music_assistant/providers/slimproto/__init__.py
  music_assistant/providers/snapcast/__init__.py
  music_assistant/providers/sonos/const.py
  music_assistant/providers/sonos/player.py
  music_assistant/providers/sonos/provider.py
  music_assistant/providers/sonos_s1/__init__.py
  music_assistant/providers/sonos_s1/player.py
Labels: new-feature

#1927 frontend-2.10.10
  pyproject.toml
  requirements_all.txt
Labels: maintenance, frontend-release

#1926 Mypy and track fallback fixes for Tidal provider
  music_assistant/providers/tidal/__init__.py
  music_assistant/providers/tidal/helpers.py
Labels: new-feature
